// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_conversation_metadata`, `append_chunk_line`, `bridge_context_item`, `bridge_memory_type_label`, `bridge_process_turn_result`, `bridge_stored_memory`, `build_embedded_memory`, `chunk_memory_bank`, `clear_source_memories`, `current_timestamp_micros`, `format_context`, `format_process_turn_context`, `from_core`, `get_session`, `get`, `infer_memory_scope`, `insert`, `lease_busy`, `normalize_database_path`, `normalize_message`, `normalize_source`, `parse_agent_id`, `registry`, `remove`, `split_long_line`, `to_i64_u64`, `to_i64`, `to_u32`, `validate_positive_u32`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DbSession`, `SessionRegistry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Open or create a MenteDB database and return a process-local session handle.
Future<OpenDatabaseResult> openDatabase(
        {required OpenDatabaseRequest request}) =>
    RustLib.instance.api.crateApiMemoryOpenDatabase(request: request);

/// Close a MenteDB session and flush persisted state.
Future<void> closeDatabase({required int handle}) =>
    RustLib.instance.api.crateApiMemoryCloseDatabase(handle: handle);

/// Flush a MenteDB session without closing it.
Future<void> flushDatabase({required int handle}) =>
    RustLib.instance.api.crateApiMemoryFlushDatabase(handle: handle);

/// Return the number of memories visible through a session.
Future<int> memoryCount({required int handle}) =>
    RustLib.instance.api.crateApiMemoryMemoryCount(handle: handle);

/// Store a single memory and return its UUID string.
Future<String> storeMemory({required StoreMemoryRequest request}) =>
    RustLib.instance.api.crateApiMemoryStoreMemory(request: request);

/// Recall memories using an MQL query string.
Future<RecallResult> recallQuery({required RecallQueryRequest request}) =>
    RustLib.instance.api.crateApiMemoryRecallQuery(request: request);

/// Vector similarity search returning the top-k results.
Future<List<SearchResult>> searchMemory(
        {required SearchMemoryRequest request}) =>
    RustLib.instance.api.crateApiMemorySearchMemory(request: request);

/// Create a typed, weighted edge between two memories.
Future<void> relateMemories({required RelateMemoriesRequest request}) =>
    RustLib.instance.api.crateApiMemoryRelateMemories(request: request);

/// Remove a memory by ID.
Future<void> forgetMemory({required ForgetMemoryRequest request}) =>
    RustLib.instance.api.crateApiMemoryForgetMemory(request: request);

/// Store user text as real MenteDB memory nodes.
Future<IngestMemoryBankResult> ingestMemoryBank(
        {required IngestMemoryBankRequest request}) =>
    RustLib.instance.api.crateApiMemoryIngestMemoryBank(request: request);

/// Recall a bounded MenteDB context for a chat prompt.
Future<RecallMemoryContextResult> recallMemoryContext(
        {required RecallMemoryContextRequest request}) =>
    RustLib.instance.api.crateApiMemoryRecallMemoryContext(request: request);

/// Store a completed user and assistant exchange as recent episodic memory.
Future<StoreConversationTurnResult> storeConversationTurn(
        {required StoreConversationTurnRequest request}) =>
    RustLib.instance.api.crateApiMemoryStoreConversationTurn(request: request);

/// Process a conversation turn through MenteDB's unified cognitive pipeline.
Future<ProcessTurnResult> processTurn({required ProcessTurnRequest request}) =>
    RustLib.instance.api.crateApiMemoryProcessTurn(request: request);

/// Build a bounded graph projection from the native MenteDB graph.
Future<BridgeGraphProjection> graphProjection(
        {required GraphProjectionRequest request}) =>
    RustLib.instance.api.crateApiMemoryGraphProjection(request: request);

/// Run MenteDB sleep maintenance under the database lease.
Future<BridgeSleepMaintenanceResult> runSleepMaintenance(
        {required RunSleepMaintenanceRequest request}) =>
    RustLib.instance.api.crateApiMemoryRunSleepMaintenance(request: request);

/// Edge type accepted by the Flutter bridge.
enum BridgeEdgeType {
  caused,
  before,
  related,
  contradicts,
  supports,
  supersedes,
  derived,
  partOf,
  ;
}

/// Renderer-neutral graph projection returned through FRB.
class BridgeGraphProjection {
  final List<BridgeGraphProjectionNode> nodes;
  final List<BridgeGraphProjectionEdge> edges;
  final int availableNodes;
  final bool truncated;

  const BridgeGraphProjection({
    required this.nodes,
    required this.edges,
    required this.availableNodes,
    required this.truncated,
  });

  @override
  int get hashCode =>
      nodes.hashCode ^
      edges.hashCode ^
      availableNodes.hashCode ^
      truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeGraphProjection &&
          runtimeType == other.runtimeType &&
          nodes == other.nodes &&
          edges == other.edges &&
          availableNodes == other.availableNodes &&
          truncated == other.truncated;
}

/// Graph edge DTO for Flutter graph renderers.
class BridgeGraphProjectionEdge {
  final String source;
  final String target;
  final BridgeEdgeType edgeType;
  final double weight;
  final String? label;
  final PlatformInt64 createdAtMicros;
  final PlatformInt64? validUntilMicros;

  const BridgeGraphProjectionEdge({
    required this.source,
    required this.target,
    required this.edgeType,
    required this.weight,
    this.label,
    required this.createdAtMicros,
    this.validUntilMicros,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      target.hashCode ^
      edgeType.hashCode ^
      weight.hashCode ^
      label.hashCode ^
      createdAtMicros.hashCode ^
      validUntilMicros.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeGraphProjectionEdge &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          target == other.target &&
          edgeType == other.edgeType &&
          weight == other.weight &&
          label == other.label &&
          createdAtMicros == other.createdAtMicros &&
          validUntilMicros == other.validUntilMicros;
}

/// Memory node DTO for Flutter graph renderers.
class BridgeGraphProjectionNode {
  final String id;
  final String label;
  final String preview;
  final BridgeMemoryType memoryType;
  final double salience;
  final double confidence;
  final List<String> tags;
  final PlatformInt64 createdAtMicros;
  final PlatformInt64 accessedAtMicros;
  final PlatformInt64? validUntilMicros;
  final int embeddingDim;

  const BridgeGraphProjectionNode({
    required this.id,
    required this.label,
    required this.preview,
    required this.memoryType,
    required this.salience,
    required this.confidence,
    required this.tags,
    required this.createdAtMicros,
    required this.accessedAtMicros,
    this.validUntilMicros,
    required this.embeddingDim,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      preview.hashCode ^
      memoryType.hashCode ^
      salience.hashCode ^
      confidence.hashCode ^
      tags.hashCode ^
      createdAtMicros.hashCode ^
      accessedAtMicros.hashCode ^
      validUntilMicros.hashCode ^
      embeddingDim.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeGraphProjectionNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          preview == other.preview &&
          memoryType == other.memoryType &&
          salience == other.salience &&
          confidence == other.confidence &&
          tags == other.tags &&
          createdAtMicros == other.createdAtMicros &&
          accessedAtMicros == other.accessedAtMicros &&
          validUntilMicros == other.validUntilMicros &&
          embeddingDim == other.embeddingDim;
}

/// Memory type accepted by the Flutter bridge.
enum BridgeMemoryType {
  episodic,
  semantic,
  procedural,
  antiPattern,
  reasoning,
  correction,
  ;
}

/// A single recalled memory with score and metadata.
class BridgeRecalledMemory {
  final String id;
  final String content;
  final double score;
  final BridgeMemoryType memoryType;
  final List<String> tags;
  final PlatformInt64 createdAtMicros;
  final double salience;
  final double confidence;

  const BridgeRecalledMemory({
    required this.id,
    required this.content,
    required this.score,
    required this.memoryType,
    required this.tags,
    required this.createdAtMicros,
    required this.salience,
    required this.confidence,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      content.hashCode ^
      score.hashCode ^
      memoryType.hashCode ^
      tags.hashCode ^
      createdAtMicros.hashCode ^
      salience.hashCode ^
      confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRecalledMemory &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          content == other.content &&
          score == other.score &&
          memoryType == other.memoryType &&
          tags == other.tags &&
          createdAtMicros == other.createdAtMicros &&
          salience == other.salience &&
          confidence == other.confidence;
}

/// Non-fatal issue reported by a sleep maintenance stage.
class BridgeSleepMaintenanceIssue {
  final String stage;
  final String? memoryId;
  final String message;

  const BridgeSleepMaintenanceIssue({
    required this.stage,
    this.memoryId,
    required this.message,
  });

  @override
  int get hashCode => stage.hashCode ^ memoryId.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSleepMaintenanceIssue &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          memoryId == other.memoryId &&
          message == other.message;
}

/// Summary of a leased sleep maintenance run.
class BridgeSleepMaintenanceResult {
  final bool leaseAcquired;
  final int processedMemories;
  final int decayUpdated;
  final int archivalEvaluated;
  final int archivalKeep;
  final int archivalArchive;
  final int archivalDelete;
  final int archivalConsolidate;
  final int archivalDeleteApplied;
  final int consolidationCandidates;
  final int consolidated;
  final List<String> consolidatedMemoryIds;
  final int entityPairsLinked;
  final int entityEdgesCreated;
  final int entityPairsAmbiguous;
  final bool enrichmentPending;
  final int enrichmentCandidates;
  final List<BridgeSleepMaintenanceIssue> issues;

  const BridgeSleepMaintenanceResult({
    required this.leaseAcquired,
    required this.processedMemories,
    required this.decayUpdated,
    required this.archivalEvaluated,
    required this.archivalKeep,
    required this.archivalArchive,
    required this.archivalDelete,
    required this.archivalConsolidate,
    required this.archivalDeleteApplied,
    required this.consolidationCandidates,
    required this.consolidated,
    required this.consolidatedMemoryIds,
    required this.entityPairsLinked,
    required this.entityEdgesCreated,
    required this.entityPairsAmbiguous,
    required this.enrichmentPending,
    required this.enrichmentCandidates,
    required this.issues,
  });

  @override
  int get hashCode =>
      leaseAcquired.hashCode ^
      processedMemories.hashCode ^
      decayUpdated.hashCode ^
      archivalEvaluated.hashCode ^
      archivalKeep.hashCode ^
      archivalArchive.hashCode ^
      archivalDelete.hashCode ^
      archivalConsolidate.hashCode ^
      archivalDeleteApplied.hashCode ^
      consolidationCandidates.hashCode ^
      consolidated.hashCode ^
      consolidatedMemoryIds.hashCode ^
      entityPairsLinked.hashCode ^
      entityEdgesCreated.hashCode ^
      entityPairsAmbiguous.hashCode ^
      enrichmentPending.hashCode ^
      enrichmentCandidates.hashCode ^
      issues.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSleepMaintenanceResult &&
          runtimeType == other.runtimeType &&
          leaseAcquired == other.leaseAcquired &&
          processedMemories == other.processedMemories &&
          decayUpdated == other.decayUpdated &&
          archivalEvaluated == other.archivalEvaluated &&
          archivalKeep == other.archivalKeep &&
          archivalArchive == other.archivalArchive &&
          archivalDelete == other.archivalDelete &&
          archivalConsolidate == other.archivalConsolidate &&
          archivalDeleteApplied == other.archivalDeleteApplied &&
          consolidationCandidates == other.consolidationCandidates &&
          consolidated == other.consolidated &&
          consolidatedMemoryIds == other.consolidatedMemoryIds &&
          entityPairsLinked == other.entityPairsLinked &&
          entityEdgesCreated == other.entityEdgesCreated &&
          entityPairsAmbiguous == other.entityPairsAmbiguous &&
          enrichmentPending == other.enrichmentPending &&
          enrichmentCandidates == other.enrichmentCandidates &&
          issues == other.issues;
}

/// Request used by the TypeScript-style `forget` API.
class ForgetMemoryRequest {
  final int handle;
  final String memoryId;
  final bool flush;

  const ForgetMemoryRequest({
    required this.handle,
    required this.memoryId,
    required this.flush,
  });

  @override
  int get hashCode => handle.hashCode ^ memoryId.hashCode ^ flush.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ForgetMemoryRequest &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          memoryId == other.memoryId &&
          flush == other.flush;
}

/// Request used to project the MenteDB graph for Flutter rendering.
class GraphProjectionRequest {
  final int handle;
  final String? center;
  final int depth;
  final int limit;
  final int labelChars;
  final int previewChars;
  final bool includeInvalidated;
  final bool includeEdges;

  const GraphProjectionRequest({
    required this.handle,
    this.center,
    required this.depth,
    required this.limit,
    required this.labelChars,
    required this.previewChars,
    required this.includeInvalidated,
    required this.includeEdges,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      center.hashCode ^
      depth.hashCode ^
      limit.hashCode ^
      labelChars.hashCode ^
      previewChars.hashCode ^
      includeInvalidated.hashCode ^
      includeEdges.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphProjectionRequest &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          center == other.center &&
          depth == other.depth &&
          limit == other.limit &&
          labelChars == other.labelChars &&
          previewChars == other.previewChars &&
          includeInvalidated == other.includeInvalidated &&
          includeEdges == other.includeEdges;
}

/// Request used to replace or append a text memory bank.
class IngestMemoryBankRequest {
  /// Database handle returned by `open_database`.
  final int handle;

  /// Raw text supplied by the user.
  final String text;

  /// Source tag used to replace or filter this memory bank.
  final String source;

  /// Classification assigned to every generated memory node.
  final BridgeMemoryType memoryType;

  /// Maximum characters per stored memory chunk.
  final int maxChunkChars;

  /// Remove existing memories tagged with this source before storing chunks.
  final bool replaceSource;

  /// Flush indexes, graph, and storage after ingest.
  final bool flush;

  const IngestMemoryBankRequest({
    required this.handle,
    required this.text,
    required this.source,
    required this.memoryType,
    required this.maxChunkChars,
    required this.replaceSource,
    required this.flush,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      text.hashCode ^
      source.hashCode ^
      memoryType.hashCode ^
      maxChunkChars.hashCode ^
      replaceSource.hashCode ^
      flush.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IngestMemoryBankRequest &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          text == other.text &&
          source == other.source &&
          memoryType == other.memoryType &&
          maxChunkChars == other.maxChunkChars &&
          replaceSource == other.replaceSource &&
          flush == other.flush;
}

/// Summary returned after ingesting a memory bank.
class IngestMemoryBankResult {
  /// Number of chunks stored as memory nodes.
  final int stored;

  /// Number of existing source memories removed before ingest.
  final int replaced;

  /// Number of memories visible after ingest.
  final int memoryCount;

  /// Stored memory IDs, encoded as strings for Dart.
  final List<String> memoryIds;

  const IngestMemoryBankResult({
    required this.stored,
    required this.replaced,
    required this.memoryCount,
    required this.memoryIds,
  });

  @override
  int get hashCode =>
      stored.hashCode ^
      replaced.hashCode ^
      memoryCount.hashCode ^
      memoryIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IngestMemoryBankResult &&
          runtimeType == other.runtimeType &&
          stored == other.stored &&
          replaced == other.replaced &&
          memoryCount == other.memoryCount &&
          memoryIds == other.memoryIds;
}

/// Request used to open or create a native MenteDB database.
class OpenDatabaseRequest {
  /// Directory where MenteDB stores WAL, pages, indexes, and graph state.
  final String path;

  /// Hash embedding dimensionality for local demo recall.
  final int embeddingDimensions;

  /// Optional stable agent identifier. A new one is generated when empty.
  final String? agentId;

  const OpenDatabaseRequest({
    required this.path,
    required this.embeddingDimensions,
    this.agentId,
  });

  @override
  int get hashCode =>
      path.hashCode ^ embeddingDimensions.hashCode ^ agentId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenDatabaseRequest &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          embeddingDimensions == other.embeddingDimensions &&
          agentId == other.agentId;
}

/// Handle and metadata for an opened native database session.
class OpenDatabaseResult {
  /// Process-local handle used by subsequent bridge calls.
  final int handle;

  /// Canonical database directory used by Rust.
  final String path;

  /// Agent ID assigned to memories created through this session.
  final String agentId;

  /// Embedding dimensionality configured for this session.
  final int embeddingDimensions;

  /// Current number of memories visible to the database.
  final int memoryCount;

  const OpenDatabaseResult({
    required this.handle,
    required this.path,
    required this.agentId,
    required this.embeddingDimensions,
    required this.memoryCount,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      path.hashCode ^
      agentId.hashCode ^
      embeddingDimensions.hashCode ^
      memoryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenDatabaseResult &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          path == other.path &&
          agentId == other.agentId &&
          embeddingDimensions == other.embeddingDimensions &&
          memoryCount == other.memoryCount;
}

/// A scored memory returned by the process_turn retrieval stage.
class ProcessTurnContextItem {
  final String id;
  final String content;
  final double score;
  final BridgeMemoryType memoryType;
  final List<String> tags;
  final PlatformInt64 createdAtMicros;
  final double salience;
  final double confidence;
  final bool isNew;
  final bool fromCache;
  final String scope;

  const ProcessTurnContextItem({
    required this.id,
    required this.content,
    required this.score,
    required this.memoryType,
    required this.tags,
    required this.createdAtMicros,
    required this.salience,
    required this.confidence,
    required this.isNew,
    required this.fromCache,
    required this.scope,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      content.hashCode ^
      score.hashCode ^
      memoryType.hashCode ^
      tags.hashCode ^
      createdAtMicros.hashCode ^
      salience.hashCode ^
      confidence.hashCode ^
      isNew.hashCode ^
      fromCache.hashCode ^
      scope.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessTurnContextItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          content == other.content &&
          score == other.score &&
          memoryType == other.memoryType &&
          tags == other.tags &&
          createdAtMicros == other.createdAtMicros &&
          salience == other.salience &&
          confidence == other.confidence &&
          isNew == other.isNew &&
          fromCache == other.fromCache &&
          scope == other.scope;
}

/// Action detected from the current turn.
class ProcessTurnDetectedAction {
  final String actionType;
  final String detail;

  const ProcessTurnDetectedAction({
    required this.actionType,
    required this.detail,
  });

  @override
  int get hashCode => actionType.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessTurnDetectedAction &&
          runtimeType == other.runtimeType &&
          actionType == other.actionType &&
          detail == other.detail;
}

/// Pain signal matched during process_turn.
class ProcessTurnPainWarning {
  final String signalId;
  final double intensity;
  final String description;

  const ProcessTurnPainWarning({
    required this.signalId,
    required this.intensity,
    required this.description,
  });

  @override
  int get hashCode =>
      signalId.hashCode ^ intensity.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessTurnPainWarning &&
          runtimeType == other.runtimeType &&
          signalId == other.signalId &&
          intensity == other.intensity &&
          description == other.description;
}

/// Memory proactively recalled because an action was detected.
class ProcessTurnProactiveRecall {
  final String memoryId;
  final String content;
  final double relevance;
  final String actionType;

  const ProcessTurnProactiveRecall({
    required this.memoryId,
    required this.content,
    required this.relevance,
    required this.actionType,
  });

  @override
  int get hashCode =>
      memoryId.hashCode ^
      content.hashCode ^
      relevance.hashCode ^
      actionType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessTurnProactiveRecall &&
          runtimeType == other.runtimeType &&
          memoryId == other.memoryId &&
          content == other.content &&
          relevance == other.relevance &&
          actionType == other.actionType;
}

/// Request used to run the full MenteDB conversation pipeline.
class ProcessTurnRequest {
  /// Database handle returned by `open_database`.
  final int handle;

  /// User message for this turn.
  final String userMessage;

  /// Assistant response when the model has already answered.
  final String? assistantResponse;

  /// Monotonic turn number chosen by the app.
  final int turnId;

  /// Optional workspace, chat, or project scope.
  final String? projectContext;

  /// Optional stable agent identifier. The session agent is used when empty.
  final String? agentId;

  /// Flush indexes, graph, and storage after processing the turn.
  final bool flush;

  const ProcessTurnRequest({
    required this.handle,
    required this.userMessage,
    this.assistantResponse,
    required this.turnId,
    this.projectContext,
    this.agentId,
    required this.flush,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      userMessage.hashCode ^
      assistantResponse.hashCode ^
      turnId.hashCode ^
      projectContext.hashCode ^
      agentId.hashCode ^
      flush.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessTurnRequest &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          userMessage == other.userMessage &&
          assistantResponse == other.assistantResponse &&
          turnId == other.turnId &&
          projectContext == other.projectContext &&
          agentId == other.agentId &&
          flush == other.flush;
}

/// Full Dart DTO for MenteDB's unified process_turn pipeline.
class ProcessTurnResult {
  final List<ProcessTurnContextItem> context;
  final String contextText;
  final int stored;
  final List<String> storedIds;
  final List<ProcessTurnStoredMemory> storedMemories;
  final String? episodicId;
  final List<ProcessTurnPainWarning> painWarnings;
  final bool cacheHit;
  final int inferenceActions;
  final List<ProcessTurnDetectedAction> detectedActions;
  final List<ProcessTurnProactiveRecall> proactiveRecalls;
  final String? correctionId;
  final double sentiment;
  final int phantomCount;
  final int contradictionCount;
  final List<String> predictedTopics;
  final int factsExtracted;
  final int edgesCreated;
  final bool enrichmentPending;
  final List<String> deltaAdded;
  final List<String> deltaRemoved;
  final int memoryCount;

  const ProcessTurnResult({
    required this.context,
    required this.contextText,
    required this.stored,
    required this.storedIds,
    required this.storedMemories,
    this.episodicId,
    required this.painWarnings,
    required this.cacheHit,
    required this.inferenceActions,
    required this.detectedActions,
    required this.proactiveRecalls,
    this.correctionId,
    required this.sentiment,
    required this.phantomCount,
    required this.contradictionCount,
    required this.predictedTopics,
    required this.factsExtracted,
    required this.edgesCreated,
    required this.enrichmentPending,
    required this.deltaAdded,
    required this.deltaRemoved,
    required this.memoryCount,
  });

  @override
  int get hashCode =>
      context.hashCode ^
      contextText.hashCode ^
      stored.hashCode ^
      storedIds.hashCode ^
      storedMemories.hashCode ^
      episodicId.hashCode ^
      painWarnings.hashCode ^
      cacheHit.hashCode ^
      inferenceActions.hashCode ^
      detectedActions.hashCode ^
      proactiveRecalls.hashCode ^
      correctionId.hashCode ^
      sentiment.hashCode ^
      phantomCount.hashCode ^
      contradictionCount.hashCode ^
      predictedTopics.hashCode ^
      factsExtracted.hashCode ^
      edgesCreated.hashCode ^
      enrichmentPending.hashCode ^
      deltaAdded.hashCode ^
      deltaRemoved.hashCode ^
      memoryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessTurnResult &&
          runtimeType == other.runtimeType &&
          context == other.context &&
          contextText == other.contextText &&
          stored == other.stored &&
          storedIds == other.storedIds &&
          storedMemories == other.storedMemories &&
          episodicId == other.episodicId &&
          painWarnings == other.painWarnings &&
          cacheHit == other.cacheHit &&
          inferenceActions == other.inferenceActions &&
          detectedActions == other.detectedActions &&
          proactiveRecalls == other.proactiveRecalls &&
          correctionId == other.correctionId &&
          sentiment == other.sentiment &&
          phantomCount == other.phantomCount &&
          contradictionCount == other.contradictionCount &&
          predictedTopics == other.predictedTopics &&
          factsExtracted == other.factsExtracted &&
          edgesCreated == other.edgesCreated &&
          enrichmentPending == other.enrichmentPending &&
          deltaAdded == other.deltaAdded &&
          deltaRemoved == other.deltaRemoved &&
          memoryCount == other.memoryCount;
}

/// A memory written during a process_turn call.
class ProcessTurnStoredMemory {
  final String id;
  final String content;
  final BridgeMemoryType memoryType;
  final List<String> tags;
  final double salience;
  final double confidence;

  const ProcessTurnStoredMemory({
    required this.id,
    required this.content,
    required this.memoryType,
    required this.tags,
    required this.salience,
    required this.confidence,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      content.hashCode ^
      memoryType.hashCode ^
      tags.hashCode ^
      salience.hashCode ^
      confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessTurnStoredMemory &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          content == other.content &&
          memoryType == other.memoryType &&
          tags == other.tags &&
          salience == other.salience &&
          confidence == other.confidence;
}

/// Request used to recall memories for a chat prompt.
class RecallMemoryContextRequest {
  /// Database handle returned by `open_database`.
  final int handle;

  /// User question used for hybrid recall.
  final String query;

  /// Maximum number of memories to retrieve.
  final int limit;

  /// Maximum characters included in the formatted context string.
  final int maxContextChars;

  /// Optional source tag filter.
  final String? source;

  const RecallMemoryContextRequest({
    required this.handle,
    required this.query,
    required this.limit,
    required this.maxContextChars,
    this.source,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      query.hashCode ^
      limit.hashCode ^
      maxContextChars.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecallMemoryContextRequest &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          query == other.query &&
          limit == other.limit &&
          maxContextChars == other.maxContextChars &&
          source == other.source;
}

/// Recall result formatted for immediate LLM prompt injection.
class RecallMemoryContextResult {
  final String context;
  final List<BridgeRecalledMemory> memories;
  final bool truncated;

  const RecallMemoryContextResult({
    required this.context,
    required this.memories,
    required this.truncated,
  });

  @override
  int get hashCode => context.hashCode ^ memories.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecallMemoryContextResult &&
          runtimeType == other.runtimeType &&
          context == other.context &&
          memories == other.memories &&
          truncated == other.truncated;
}

/// Request used by the TypeScript-style MQL `recall` API.
class RecallQueryRequest {
  final int handle;
  final String query;

  const RecallQueryRequest({
    required this.handle,
    required this.query,
  });

  @override
  int get hashCode => handle.hashCode ^ query.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecallQueryRequest &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          query == other.query;
}

/// MQL recall result compatible with the TypeScript SDK shape.
class RecallResult {
  final String text;
  final int totalTokens;
  final int memoryCount;

  const RecallResult({
    required this.text,
    required this.totalTokens,
    required this.memoryCount,
  });

  @override
  int get hashCode =>
      text.hashCode ^ totalTokens.hashCode ^ memoryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecallResult &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          totalTokens == other.totalTokens &&
          memoryCount == other.memoryCount;
}

/// Request used by the TypeScript-style `relate` API.
class RelateMemoriesRequest {
  final int handle;
  final String source;
  final String target;
  final BridgeEdgeType edgeType;
  final double weight;
  final bool flush;

  const RelateMemoriesRequest({
    required this.handle,
    required this.source,
    required this.target,
    required this.edgeType,
    required this.weight,
    required this.flush,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      source.hashCode ^
      target.hashCode ^
      edgeType.hashCode ^
      weight.hashCode ^
      flush.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelateMemoriesRequest &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          source == other.source &&
          target == other.target &&
          edgeType == other.edgeType &&
          weight == other.weight &&
          flush == other.flush;
}

/// Request used to run bounded sleep maintenance from Flutter background jobs.
class RunSleepMaintenanceRequest {
  final int handle;
  final int maxMemories;
  final bool applyDecay;
  final bool evaluateArchival;
  final bool applyArchivalDeletes;
  final bool runConsolidation;
  final int maxConsolidationClusters;
  final int consolidationMinClusterSize;
  final double consolidationSimilarityThreshold;
  final bool linkEntities;

  const RunSleepMaintenanceRequest({
    required this.handle,
    required this.maxMemories,
    required this.applyDecay,
    required this.evaluateArchival,
    required this.applyArchivalDeletes,
    required this.runConsolidation,
    required this.maxConsolidationClusters,
    required this.consolidationMinClusterSize,
    required this.consolidationSimilarityThreshold,
    required this.linkEntities,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      maxMemories.hashCode ^
      applyDecay.hashCode ^
      evaluateArchival.hashCode ^
      applyArchivalDeletes.hashCode ^
      runConsolidation.hashCode ^
      maxConsolidationClusters.hashCode ^
      consolidationMinClusterSize.hashCode ^
      consolidationSimilarityThreshold.hashCode ^
      linkEntities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RunSleepMaintenanceRequest &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          maxMemories == other.maxMemories &&
          applyDecay == other.applyDecay &&
          evaluateArchival == other.evaluateArchival &&
          applyArchivalDeletes == other.applyArchivalDeletes &&
          runConsolidation == other.runConsolidation &&
          maxConsolidationClusters == other.maxConsolidationClusters &&
          consolidationMinClusterSize == other.consolidationMinClusterSize &&
          consolidationSimilarityThreshold ==
              other.consolidationSimilarityThreshold &&
          linkEntities == other.linkEntities;
}

/// Request used by the TypeScript-style vector `search` API.
class SearchMemoryRequest {
  final int handle;
  final Float64List embedding;
  final int k;

  const SearchMemoryRequest({
    required this.handle,
    required this.embedding,
    required this.k,
  });

  @override
  int get hashCode => handle.hashCode ^ embedding.hashCode ^ k.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchMemoryRequest &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          embedding == other.embedding &&
          k == other.k;
}

/// Vector search result compatible with the TypeScript SDK shape.
class SearchResult {
  final String id;
  final double score;

  const SearchResult({
    required this.id,
    required this.score,
  });

  @override
  int get hashCode => id.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          score == other.score;
}

/// Request used to persist a completed chat turn as recent episodic memory.
class StoreConversationTurnRequest {
  /// Database handle returned by `open_database`.
  final int handle;

  /// Stable conversation identifier chosen by the app.
  final String conversationId;

  /// Monotonic turn index within the conversation.
  final int turnIndex;

  /// User message to persist.
  final String userMessage;

  /// Assistant message to persist.
  final String assistantMessage;

  /// Source tag used to retrieve or maintain recent chat separately.
  final String source;

  /// Flush indexes, graph, and storage after storing the turn.
  final bool flush;

  const StoreConversationTurnRequest({
    required this.handle,
    required this.conversationId,
    required this.turnIndex,
    required this.userMessage,
    required this.assistantMessage,
    required this.source,
    required this.flush,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      conversationId.hashCode ^
      turnIndex.hashCode ^
      userMessage.hashCode ^
      assistantMessage.hashCode ^
      source.hashCode ^
      flush.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoreConversationTurnRequest &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          conversationId == other.conversationId &&
          turnIndex == other.turnIndex &&
          userMessage == other.userMessage &&
          assistantMessage == other.assistantMessage &&
          source == other.source &&
          flush == other.flush;
}

/// Summary returned after storing a completed chat turn.
class StoreConversationTurnResult {
  final int stored;
  final String userMemoryId;
  final String assistantMemoryId;
  final int memoryCount;

  const StoreConversationTurnResult({
    required this.stored,
    required this.userMemoryId,
    required this.assistantMemoryId,
    required this.memoryCount,
  });

  @override
  int get hashCode =>
      stored.hashCode ^
      userMemoryId.hashCode ^
      assistantMemoryId.hashCode ^
      memoryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoreConversationTurnResult &&
          runtimeType == other.runtimeType &&
          stored == other.stored &&
          userMemoryId == other.userMemoryId &&
          assistantMemoryId == other.assistantMemoryId &&
          memoryCount == other.memoryCount;
}

/// Request used by the TypeScript-style low-level `store` API.
class StoreMemoryRequest {
  final int handle;
  final String content;
  final BridgeMemoryType memoryType;
  final Float64List embedding;
  final String? agentId;
  final List<String> tags;
  final bool flush;

  const StoreMemoryRequest({
    required this.handle,
    required this.content,
    required this.memoryType,
    required this.embedding,
    this.agentId,
    required this.tags,
    required this.flush,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      content.hashCode ^
      memoryType.hashCode ^
      embedding.hashCode ^
      agentId.hashCode ^
      tags.hashCode ^
      flush.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoreMemoryRequest &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          content == other.content &&
          memoryType == other.memoryType &&
          embedding == other.embedding &&
          agentId == other.agentId &&
          tags == other.tags &&
          flush == other.flush;
}
