// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0-beta.2";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -173114382;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__memory__close_database_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "close_database",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::memory::close_database(api_handle)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__memory__flush_database_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "flush_database",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::memory::flush_database(api_handle)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__memory__ingest_memory_bank_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ingest_memory_bank",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::memory::IngestMemoryBankRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::memory::ingest_memory_bank(api_request)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__memory__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::memory::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__memory__memory_count_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "memory_count",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::memory::memory_count(api_handle)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__memory__open_database_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "open_database",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::memory::OpenDatabaseRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::memory::open_database(api_request)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__memory__recall_memory_context_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "recall_memory_context",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::memory::RecallMemoryContextRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::memory::recall_memory_context(api_request)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__memory__run_sleep_maintenance_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "run_sleep_maintenance",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::memory::RunSleepMaintenanceRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::memory::run_sleep_maintenance(api_request)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::memory::BridgeMemoryType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::memory::BridgeMemoryType::Episodic,
            1 => crate::api::memory::BridgeMemoryType::Semantic,
            2 => crate::api::memory::BridgeMemoryType::Procedural,
            3 => crate::api::memory::BridgeMemoryType::AntiPattern,
            4 => crate::api::memory::BridgeMemoryType::Reasoning,
            5 => crate::api::memory::BridgeMemoryType::Correction,
            _ => unreachable!("Invalid variant for BridgeMemoryType: {}", inner),
        };
    }
}

impl SseDecode for crate::api::memory::BridgeRecalledMemory {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_content = <String>::sse_decode(deserializer);
        let mut var_score = <f32>::sse_decode(deserializer);
        let mut var_memoryType = <crate::api::memory::BridgeMemoryType>::sse_decode(deserializer);
        let mut var_tags = <Vec<String>>::sse_decode(deserializer);
        let mut var_createdAtMicros = <i64>::sse_decode(deserializer);
        let mut var_salience = <f32>::sse_decode(deserializer);
        let mut var_confidence = <f32>::sse_decode(deserializer);
        return crate::api::memory::BridgeRecalledMemory {
            id: var_id,
            content: var_content,
            score: var_score,
            memory_type: var_memoryType,
            tags: var_tags,
            created_at_micros: var_createdAtMicros,
            salience: var_salience,
            confidence: var_confidence,
        };
    }
}

impl SseDecode for crate::api::memory::BridgeSleepMaintenanceIssue {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_stage = <String>::sse_decode(deserializer);
        let mut var_memoryId = <Option<String>>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        return crate::api::memory::BridgeSleepMaintenanceIssue {
            stage: var_stage,
            memory_id: var_memoryId,
            message: var_message,
        };
    }
}

impl SseDecode for crate::api::memory::BridgeSleepMaintenanceResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_leaseAcquired = <bool>::sse_decode(deserializer);
        let mut var_processedMemories = <u32>::sse_decode(deserializer);
        let mut var_decayUpdated = <u32>::sse_decode(deserializer);
        let mut var_archivalEvaluated = <u32>::sse_decode(deserializer);
        let mut var_archivalKeep = <u32>::sse_decode(deserializer);
        let mut var_archivalArchive = <u32>::sse_decode(deserializer);
        let mut var_archivalDelete = <u32>::sse_decode(deserializer);
        let mut var_archivalConsolidate = <u32>::sse_decode(deserializer);
        let mut var_archivalDeleteApplied = <u32>::sse_decode(deserializer);
        let mut var_consolidationCandidates = <u32>::sse_decode(deserializer);
        let mut var_consolidated = <u32>::sse_decode(deserializer);
        let mut var_consolidatedMemoryIds = <Vec<String>>::sse_decode(deserializer);
        let mut var_entityPairsLinked = <u32>::sse_decode(deserializer);
        let mut var_entityEdgesCreated = <u32>::sse_decode(deserializer);
        let mut var_entityPairsAmbiguous = <u32>::sse_decode(deserializer);
        let mut var_enrichmentPending = <bool>::sse_decode(deserializer);
        let mut var_enrichmentCandidates = <u32>::sse_decode(deserializer);
        let mut var_issues =
            <Vec<crate::api::memory::BridgeSleepMaintenanceIssue>>::sse_decode(deserializer);
        return crate::api::memory::BridgeSleepMaintenanceResult {
            lease_acquired: var_leaseAcquired,
            processed_memories: var_processedMemories,
            decay_updated: var_decayUpdated,
            archival_evaluated: var_archivalEvaluated,
            archival_keep: var_archivalKeep,
            archival_archive: var_archivalArchive,
            archival_delete: var_archivalDelete,
            archival_consolidate: var_archivalConsolidate,
            archival_delete_applied: var_archivalDeleteApplied,
            consolidation_candidates: var_consolidationCandidates,
            consolidated: var_consolidated,
            consolidated_memory_ids: var_consolidatedMemoryIds,
            entity_pairs_linked: var_entityPairsLinked,
            entity_edges_created: var_entityEdgesCreated,
            entity_pairs_ambiguous: var_entityPairsAmbiguous,
            enrichment_pending: var_enrichmentPending,
            enrichment_candidates: var_enrichmentCandidates,
            issues: var_issues,
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::memory::IngestMemoryBankRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_handle = <u32>::sse_decode(deserializer);
        let mut var_text = <String>::sse_decode(deserializer);
        let mut var_source = <String>::sse_decode(deserializer);
        let mut var_memoryType = <crate::api::memory::BridgeMemoryType>::sse_decode(deserializer);
        let mut var_maxChunkChars = <u32>::sse_decode(deserializer);
        let mut var_replaceSource = <bool>::sse_decode(deserializer);
        let mut var_flush = <bool>::sse_decode(deserializer);
        return crate::api::memory::IngestMemoryBankRequest {
            handle: var_handle,
            text: var_text,
            source: var_source,
            memory_type: var_memoryType,
            max_chunk_chars: var_maxChunkChars,
            replace_source: var_replaceSource,
            flush: var_flush,
        };
    }
}

impl SseDecode for crate::api::memory::IngestMemoryBankResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_stored = <u32>::sse_decode(deserializer);
        let mut var_replaced = <u32>::sse_decode(deserializer);
        let mut var_memoryCount = <u32>::sse_decode(deserializer);
        let mut var_memoryIds = <Vec<String>>::sse_decode(deserializer);
        return crate::api::memory::IngestMemoryBankResult {
            stored: var_stored,
            replaced: var_replaced,
            memory_count: var_memoryCount,
            memory_ids: var_memoryIds,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::memory::BridgeRecalledMemory> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::memory::BridgeRecalledMemory>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::memory::BridgeSleepMaintenanceIssue> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::memory::BridgeSleepMaintenanceIssue>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::memory::OpenDatabaseRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_embeddingDimensions = <u32>::sse_decode(deserializer);
        let mut var_agentId = <Option<String>>::sse_decode(deserializer);
        return crate::api::memory::OpenDatabaseRequest {
            path: var_path,
            embedding_dimensions: var_embeddingDimensions,
            agent_id: var_agentId,
        };
    }
}

impl SseDecode for crate::api::memory::OpenDatabaseResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_handle = <u32>::sse_decode(deserializer);
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_agentId = <String>::sse_decode(deserializer);
        let mut var_embeddingDimensions = <u32>::sse_decode(deserializer);
        let mut var_memoryCount = <u32>::sse_decode(deserializer);
        return crate::api::memory::OpenDatabaseResult {
            handle: var_handle,
            path: var_path,
            agent_id: var_agentId,
            embedding_dimensions: var_embeddingDimensions,
            memory_count: var_memoryCount,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::memory::RecallMemoryContextRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_handle = <u32>::sse_decode(deserializer);
        let mut var_query = <String>::sse_decode(deserializer);
        let mut var_limit = <u32>::sse_decode(deserializer);
        let mut var_maxContextChars = <u32>::sse_decode(deserializer);
        let mut var_source = <Option<String>>::sse_decode(deserializer);
        return crate::api::memory::RecallMemoryContextRequest {
            handle: var_handle,
            query: var_query,
            limit: var_limit,
            max_context_chars: var_maxContextChars,
            source: var_source,
        };
    }
}

impl SseDecode for crate::api::memory::RecallMemoryContextResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_context = <String>::sse_decode(deserializer);
        let mut var_memories =
            <Vec<crate::api::memory::BridgeRecalledMemory>>::sse_decode(deserializer);
        let mut var_truncated = <bool>::sse_decode(deserializer);
        return crate::api::memory::RecallMemoryContextResult {
            context: var_context,
            memories: var_memories,
            truncated: var_truncated,
        };
    }
}

impl SseDecode for crate::api::memory::RunSleepMaintenanceRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_handle = <u32>::sse_decode(deserializer);
        let mut var_maxMemories = <u32>::sse_decode(deserializer);
        let mut var_applyDecay = <bool>::sse_decode(deserializer);
        let mut var_evaluateArchival = <bool>::sse_decode(deserializer);
        let mut var_applyArchivalDeletes = <bool>::sse_decode(deserializer);
        let mut var_runConsolidation = <bool>::sse_decode(deserializer);
        let mut var_maxConsolidationClusters = <u32>::sse_decode(deserializer);
        let mut var_consolidationMinClusterSize = <u32>::sse_decode(deserializer);
        let mut var_consolidationSimilarityThreshold = <f32>::sse_decode(deserializer);
        let mut var_linkEntities = <bool>::sse_decode(deserializer);
        return crate::api::memory::RunSleepMaintenanceRequest {
            handle: var_handle,
            max_memories: var_maxMemories,
            apply_decay: var_applyDecay,
            evaluate_archival: var_evaluateArchival,
            apply_archival_deletes: var_applyArchivalDeletes,
            run_consolidation: var_runConsolidation,
            max_consolidation_clusters: var_maxConsolidationClusters,
            consolidation_min_cluster_size: var_consolidationMinClusterSize,
            consolidation_similarity_threshold: var_consolidationSimilarityThreshold,
            link_entities: var_linkEntities,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__memory__close_database_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__memory__flush_database_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__memory__ingest_memory_bank_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__memory__init_app_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__memory__memory_count_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__memory__open_database_impl(port, ptr, rust_vec_len, data_len),
        7 => {
            wire__crate__api__memory__recall_memory_context_impl(port, ptr, rust_vec_len, data_len)
        }
        8 => {
            wire__crate__api__memory__run_sleep_maintenance_impl(port, ptr, rust_vec_len, data_len)
        }
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::memory::BridgeMemoryType {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Episodic => 0.into_dart(),
            Self::Semantic => 1.into_dart(),
            Self::Procedural => 2.into_dart(),
            Self::AntiPattern => 3.into_dart(),
            Self::Reasoning => 4.into_dart(),
            Self::Correction => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::memory::BridgeMemoryType
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::memory::BridgeMemoryType>
    for crate::api::memory::BridgeMemoryType
{
    fn into_into_dart(self) -> crate::api::memory::BridgeMemoryType {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::memory::BridgeRecalledMemory {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.content.into_into_dart().into_dart(),
            self.score.into_into_dart().into_dart(),
            self.memory_type.into_into_dart().into_dart(),
            self.tags.into_into_dart().into_dart(),
            self.created_at_micros.into_into_dart().into_dart(),
            self.salience.into_into_dart().into_dart(),
            self.confidence.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::memory::BridgeRecalledMemory
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::memory::BridgeRecalledMemory>
    for crate::api::memory::BridgeRecalledMemory
{
    fn into_into_dart(self) -> crate::api::memory::BridgeRecalledMemory {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::memory::BridgeSleepMaintenanceIssue {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.stage.into_into_dart().into_dart(),
            self.memory_id.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::memory::BridgeSleepMaintenanceIssue
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::memory::BridgeSleepMaintenanceIssue>
    for crate::api::memory::BridgeSleepMaintenanceIssue
{
    fn into_into_dart(self) -> crate::api::memory::BridgeSleepMaintenanceIssue {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::memory::BridgeSleepMaintenanceResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.lease_acquired.into_into_dart().into_dart(),
            self.processed_memories.into_into_dart().into_dart(),
            self.decay_updated.into_into_dart().into_dart(),
            self.archival_evaluated.into_into_dart().into_dart(),
            self.archival_keep.into_into_dart().into_dart(),
            self.archival_archive.into_into_dart().into_dart(),
            self.archival_delete.into_into_dart().into_dart(),
            self.archival_consolidate.into_into_dart().into_dart(),
            self.archival_delete_applied.into_into_dart().into_dart(),
            self.consolidation_candidates.into_into_dart().into_dart(),
            self.consolidated.into_into_dart().into_dart(),
            self.consolidated_memory_ids.into_into_dart().into_dart(),
            self.entity_pairs_linked.into_into_dart().into_dart(),
            self.entity_edges_created.into_into_dart().into_dart(),
            self.entity_pairs_ambiguous.into_into_dart().into_dart(),
            self.enrichment_pending.into_into_dart().into_dart(),
            self.enrichment_candidates.into_into_dart().into_dart(),
            self.issues.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::memory::BridgeSleepMaintenanceResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::memory::BridgeSleepMaintenanceResult>
    for crate::api::memory::BridgeSleepMaintenanceResult
{
    fn into_into_dart(self) -> crate::api::memory::BridgeSleepMaintenanceResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::memory::IngestMemoryBankRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.handle.into_into_dart().into_dart(),
            self.text.into_into_dart().into_dart(),
            self.source.into_into_dart().into_dart(),
            self.memory_type.into_into_dart().into_dart(),
            self.max_chunk_chars.into_into_dart().into_dart(),
            self.replace_source.into_into_dart().into_dart(),
            self.flush.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::memory::IngestMemoryBankRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::memory::IngestMemoryBankRequest>
    for crate::api::memory::IngestMemoryBankRequest
{
    fn into_into_dart(self) -> crate::api::memory::IngestMemoryBankRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::memory::IngestMemoryBankResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.stored.into_into_dart().into_dart(),
            self.replaced.into_into_dart().into_dart(),
            self.memory_count.into_into_dart().into_dart(),
            self.memory_ids.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::memory::IngestMemoryBankResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::memory::IngestMemoryBankResult>
    for crate::api::memory::IngestMemoryBankResult
{
    fn into_into_dart(self) -> crate::api::memory::IngestMemoryBankResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::memory::OpenDatabaseRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.path.into_into_dart().into_dart(),
            self.embedding_dimensions.into_into_dart().into_dart(),
            self.agent_id.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::memory::OpenDatabaseRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::memory::OpenDatabaseRequest>
    for crate::api::memory::OpenDatabaseRequest
{
    fn into_into_dart(self) -> crate::api::memory::OpenDatabaseRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::memory::OpenDatabaseResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.handle.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
            self.agent_id.into_into_dart().into_dart(),
            self.embedding_dimensions.into_into_dart().into_dart(),
            self.memory_count.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::memory::OpenDatabaseResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::memory::OpenDatabaseResult>
    for crate::api::memory::OpenDatabaseResult
{
    fn into_into_dart(self) -> crate::api::memory::OpenDatabaseResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::memory::RecallMemoryContextRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.handle.into_into_dart().into_dart(),
            self.query.into_into_dart().into_dart(),
            self.limit.into_into_dart().into_dart(),
            self.max_context_chars.into_into_dart().into_dart(),
            self.source.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::memory::RecallMemoryContextRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::memory::RecallMemoryContextRequest>
    for crate::api::memory::RecallMemoryContextRequest
{
    fn into_into_dart(self) -> crate::api::memory::RecallMemoryContextRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::memory::RecallMemoryContextResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.context.into_into_dart().into_dart(),
            self.memories.into_into_dart().into_dart(),
            self.truncated.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::memory::RecallMemoryContextResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::memory::RecallMemoryContextResult>
    for crate::api::memory::RecallMemoryContextResult
{
    fn into_into_dart(self) -> crate::api::memory::RecallMemoryContextResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::memory::RunSleepMaintenanceRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.handle.into_into_dart().into_dart(),
            self.max_memories.into_into_dart().into_dart(),
            self.apply_decay.into_into_dart().into_dart(),
            self.evaluate_archival.into_into_dart().into_dart(),
            self.apply_archival_deletes.into_into_dart().into_dart(),
            self.run_consolidation.into_into_dart().into_dart(),
            self.max_consolidation_clusters.into_into_dart().into_dart(),
            self.consolidation_min_cluster_size
                .into_into_dart()
                .into_dart(),
            self.consolidation_similarity_threshold
                .into_into_dart()
                .into_dart(),
            self.link_entities.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::memory::RunSleepMaintenanceRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::memory::RunSleepMaintenanceRequest>
    for crate::api::memory::RunSleepMaintenanceRequest
{
    fn into_into_dart(self) -> crate::api::memory::RunSleepMaintenanceRequest {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::memory::BridgeMemoryType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::memory::BridgeMemoryType::Episodic => 0,
                crate::api::memory::BridgeMemoryType::Semantic => 1,
                crate::api::memory::BridgeMemoryType::Procedural => 2,
                crate::api::memory::BridgeMemoryType::AntiPattern => 3,
                crate::api::memory::BridgeMemoryType::Reasoning => 4,
                crate::api::memory::BridgeMemoryType::Correction => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::memory::BridgeRecalledMemory {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.content, serializer);
        <f32>::sse_encode(self.score, serializer);
        <crate::api::memory::BridgeMemoryType>::sse_encode(self.memory_type, serializer);
        <Vec<String>>::sse_encode(self.tags, serializer);
        <i64>::sse_encode(self.created_at_micros, serializer);
        <f32>::sse_encode(self.salience, serializer);
        <f32>::sse_encode(self.confidence, serializer);
    }
}

impl SseEncode for crate::api::memory::BridgeSleepMaintenanceIssue {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.stage, serializer);
        <Option<String>>::sse_encode(self.memory_id, serializer);
        <String>::sse_encode(self.message, serializer);
    }
}

impl SseEncode for crate::api::memory::BridgeSleepMaintenanceResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.lease_acquired, serializer);
        <u32>::sse_encode(self.processed_memories, serializer);
        <u32>::sse_encode(self.decay_updated, serializer);
        <u32>::sse_encode(self.archival_evaluated, serializer);
        <u32>::sse_encode(self.archival_keep, serializer);
        <u32>::sse_encode(self.archival_archive, serializer);
        <u32>::sse_encode(self.archival_delete, serializer);
        <u32>::sse_encode(self.archival_consolidate, serializer);
        <u32>::sse_encode(self.archival_delete_applied, serializer);
        <u32>::sse_encode(self.consolidation_candidates, serializer);
        <u32>::sse_encode(self.consolidated, serializer);
        <Vec<String>>::sse_encode(self.consolidated_memory_ids, serializer);
        <u32>::sse_encode(self.entity_pairs_linked, serializer);
        <u32>::sse_encode(self.entity_edges_created, serializer);
        <u32>::sse_encode(self.entity_pairs_ambiguous, serializer);
        <bool>::sse_encode(self.enrichment_pending, serializer);
        <u32>::sse_encode(self.enrichment_candidates, serializer);
        <Vec<crate::api::memory::BridgeSleepMaintenanceIssue>>::sse_encode(self.issues, serializer);
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::memory::IngestMemoryBankRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.handle, serializer);
        <String>::sse_encode(self.text, serializer);
        <String>::sse_encode(self.source, serializer);
        <crate::api::memory::BridgeMemoryType>::sse_encode(self.memory_type, serializer);
        <u32>::sse_encode(self.max_chunk_chars, serializer);
        <bool>::sse_encode(self.replace_source, serializer);
        <bool>::sse_encode(self.flush, serializer);
    }
}

impl SseEncode for crate::api::memory::IngestMemoryBankResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.stored, serializer);
        <u32>::sse_encode(self.replaced, serializer);
        <u32>::sse_encode(self.memory_count, serializer);
        <Vec<String>>::sse_encode(self.memory_ids, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::memory::BridgeRecalledMemory> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::memory::BridgeRecalledMemory>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::memory::BridgeSleepMaintenanceIssue> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::memory::BridgeSleepMaintenanceIssue>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::memory::OpenDatabaseRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.path, serializer);
        <u32>::sse_encode(self.embedding_dimensions, serializer);
        <Option<String>>::sse_encode(self.agent_id, serializer);
    }
}

impl SseEncode for crate::api::memory::OpenDatabaseResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.handle, serializer);
        <String>::sse_encode(self.path, serializer);
        <String>::sse_encode(self.agent_id, serializer);
        <u32>::sse_encode(self.embedding_dimensions, serializer);
        <u32>::sse_encode(self.memory_count, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::memory::RecallMemoryContextRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.handle, serializer);
        <String>::sse_encode(self.query, serializer);
        <u32>::sse_encode(self.limit, serializer);
        <u32>::sse_encode(self.max_context_chars, serializer);
        <Option<String>>::sse_encode(self.source, serializer);
    }
}

impl SseEncode for crate::api::memory::RecallMemoryContextResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.context, serializer);
        <Vec<crate::api::memory::BridgeRecalledMemory>>::sse_encode(self.memories, serializer);
        <bool>::sse_encode(self.truncated, serializer);
    }
}

impl SseEncode for crate::api::memory::RunSleepMaintenanceRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.handle, serializer);
        <u32>::sse_encode(self.max_memories, serializer);
        <bool>::sse_encode(self.apply_decay, serializer);
        <bool>::sse_encode(self.evaluate_archival, serializer);
        <bool>::sse_encode(self.apply_archival_deletes, serializer);
        <bool>::sse_encode(self.run_consolidation, serializer);
        <u32>::sse_encode(self.max_consolidation_clusters, serializer);
        <u32>::sse_encode(self.consolidation_min_cluster_size, serializer);
        <f32>::sse_encode(self.consolidation_similarity_threshold, serializer);
        <bool>::sse_encode(self.link_entities, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
