// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/memory.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ForgetMemoryRequest dco_decode_box_autoadd_forget_memory_request(dynamic raw);

  @protected
  GraphProjectionRequest dco_decode_box_autoadd_graph_projection_request(
      dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  IngestMemoryBankRequest dco_decode_box_autoadd_ingest_memory_bank_request(
      dynamic raw);

  @protected
  OpenDatabaseRequest dco_decode_box_autoadd_open_database_request(dynamic raw);

  @protected
  ProcessTurnRequest dco_decode_box_autoadd_process_turn_request(dynamic raw);

  @protected
  RecallMemoryContextRequest
      dco_decode_box_autoadd_recall_memory_context_request(dynamic raw);

  @protected
  RecallQueryRequest dco_decode_box_autoadd_recall_query_request(dynamic raw);

  @protected
  RelateMemoriesRequest dco_decode_box_autoadd_relate_memories_request(
      dynamic raw);

  @protected
  RunSleepMaintenanceRequest
      dco_decode_box_autoadd_run_sleep_maintenance_request(dynamic raw);

  @protected
  SearchMemoryRequest dco_decode_box_autoadd_search_memory_request(dynamic raw);

  @protected
  StoreConversationTurnRequest
      dco_decode_box_autoadd_store_conversation_turn_request(dynamic raw);

  @protected
  StoreMemoryRequest dco_decode_box_autoadd_store_memory_request(dynamic raw);

  @protected
  BridgeEdgeType dco_decode_bridge_edge_type(dynamic raw);

  @protected
  BridgeGraphProjection dco_decode_bridge_graph_projection(dynamic raw);

  @protected
  BridgeGraphProjectionEdge dco_decode_bridge_graph_projection_edge(
      dynamic raw);

  @protected
  BridgeGraphProjectionNode dco_decode_bridge_graph_projection_node(
      dynamic raw);

  @protected
  BridgeMemoryType dco_decode_bridge_memory_type(dynamic raw);

  @protected
  BridgeRecalledMemory dco_decode_bridge_recalled_memory(dynamic raw);

  @protected
  BridgeSleepMaintenanceIssue dco_decode_bridge_sleep_maintenance_issue(
      dynamic raw);

  @protected
  BridgeSleepMaintenanceResult dco_decode_bridge_sleep_maintenance_result(
      dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  ForgetMemoryRequest dco_decode_forget_memory_request(dynamic raw);

  @protected
  GraphProjectionRequest dco_decode_graph_projection_request(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IngestMemoryBankRequest dco_decode_ingest_memory_bank_request(dynamic raw);

  @protected
  IngestMemoryBankResult dco_decode_ingest_memory_bank_result(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BridgeGraphProjectionEdge> dco_decode_list_bridge_graph_projection_edge(
      dynamic raw);

  @protected
  List<BridgeGraphProjectionNode> dco_decode_list_bridge_graph_projection_node(
      dynamic raw);

  @protected
  List<BridgeRecalledMemory> dco_decode_list_bridge_recalled_memory(
      dynamic raw);

  @protected
  List<BridgeSleepMaintenanceIssue>
      dco_decode_list_bridge_sleep_maintenance_issue(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProcessTurnContextItem> dco_decode_list_process_turn_context_item(
      dynamic raw);

  @protected
  List<ProcessTurnDetectedAction> dco_decode_list_process_turn_detected_action(
      dynamic raw);

  @protected
  List<ProcessTurnPainWarning> dco_decode_list_process_turn_pain_warning(
      dynamic raw);

  @protected
  List<ProcessTurnProactiveRecall>
      dco_decode_list_process_turn_proactive_recall(dynamic raw);

  @protected
  List<ProcessTurnStoredMemory> dco_decode_list_process_turn_stored_memory(
      dynamic raw);

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw);

  @protected
  OpenDatabaseRequest dco_decode_open_database_request(dynamic raw);

  @protected
  OpenDatabaseResult dco_decode_open_database_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ProcessTurnContextItem dco_decode_process_turn_context_item(dynamic raw);

  @protected
  ProcessTurnDetectedAction dco_decode_process_turn_detected_action(
      dynamic raw);

  @protected
  ProcessTurnPainWarning dco_decode_process_turn_pain_warning(dynamic raw);

  @protected
  ProcessTurnProactiveRecall dco_decode_process_turn_proactive_recall(
      dynamic raw);

  @protected
  ProcessTurnRequest dco_decode_process_turn_request(dynamic raw);

  @protected
  ProcessTurnResult dco_decode_process_turn_result(dynamic raw);

  @protected
  ProcessTurnStoredMemory dco_decode_process_turn_stored_memory(dynamic raw);

  @protected
  RecallMemoryContextRequest dco_decode_recall_memory_context_request(
      dynamic raw);

  @protected
  RecallMemoryContextResult dco_decode_recall_memory_context_result(
      dynamic raw);

  @protected
  RecallQueryRequest dco_decode_recall_query_request(dynamic raw);

  @protected
  RecallResult dco_decode_recall_result(dynamic raw);

  @protected
  RelateMemoriesRequest dco_decode_relate_memories_request(dynamic raw);

  @protected
  RunSleepMaintenanceRequest dco_decode_run_sleep_maintenance_request(
      dynamic raw);

  @protected
  SearchMemoryRequest dco_decode_search_memory_request(dynamic raw);

  @protected
  SearchResult dco_decode_search_result(dynamic raw);

  @protected
  StoreConversationTurnRequest dco_decode_store_conversation_turn_request(
      dynamic raw);

  @protected
  StoreConversationTurnResult dco_decode_store_conversation_turn_result(
      dynamic raw);

  @protected
  StoreMemoryRequest dco_decode_store_memory_request(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ForgetMemoryRequest sse_decode_box_autoadd_forget_memory_request(
      SseDeserializer deserializer);

  @protected
  GraphProjectionRequest sse_decode_box_autoadd_graph_projection_request(
      SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  IngestMemoryBankRequest sse_decode_box_autoadd_ingest_memory_bank_request(
      SseDeserializer deserializer);

  @protected
  OpenDatabaseRequest sse_decode_box_autoadd_open_database_request(
      SseDeserializer deserializer);

  @protected
  ProcessTurnRequest sse_decode_box_autoadd_process_turn_request(
      SseDeserializer deserializer);

  @protected
  RecallMemoryContextRequest
      sse_decode_box_autoadd_recall_memory_context_request(
          SseDeserializer deserializer);

  @protected
  RecallQueryRequest sse_decode_box_autoadd_recall_query_request(
      SseDeserializer deserializer);

  @protected
  RelateMemoriesRequest sse_decode_box_autoadd_relate_memories_request(
      SseDeserializer deserializer);

  @protected
  RunSleepMaintenanceRequest
      sse_decode_box_autoadd_run_sleep_maintenance_request(
          SseDeserializer deserializer);

  @protected
  SearchMemoryRequest sse_decode_box_autoadd_search_memory_request(
      SseDeserializer deserializer);

  @protected
  StoreConversationTurnRequest
      sse_decode_box_autoadd_store_conversation_turn_request(
          SseDeserializer deserializer);

  @protected
  StoreMemoryRequest sse_decode_box_autoadd_store_memory_request(
      SseDeserializer deserializer);

  @protected
  BridgeEdgeType sse_decode_bridge_edge_type(SseDeserializer deserializer);

  @protected
  BridgeGraphProjection sse_decode_bridge_graph_projection(
      SseDeserializer deserializer);

  @protected
  BridgeGraphProjectionEdge sse_decode_bridge_graph_projection_edge(
      SseDeserializer deserializer);

  @protected
  BridgeGraphProjectionNode sse_decode_bridge_graph_projection_node(
      SseDeserializer deserializer);

  @protected
  BridgeMemoryType sse_decode_bridge_memory_type(SseDeserializer deserializer);

  @protected
  BridgeRecalledMemory sse_decode_bridge_recalled_memory(
      SseDeserializer deserializer);

  @protected
  BridgeSleepMaintenanceIssue sse_decode_bridge_sleep_maintenance_issue(
      SseDeserializer deserializer);

  @protected
  BridgeSleepMaintenanceResult sse_decode_bridge_sleep_maintenance_result(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  ForgetMemoryRequest sse_decode_forget_memory_request(
      SseDeserializer deserializer);

  @protected
  GraphProjectionRequest sse_decode_graph_projection_request(
      SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IngestMemoryBankRequest sse_decode_ingest_memory_bank_request(
      SseDeserializer deserializer);

  @protected
  IngestMemoryBankResult sse_decode_ingest_memory_bank_result(
      SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BridgeGraphProjectionEdge> sse_decode_list_bridge_graph_projection_edge(
      SseDeserializer deserializer);

  @protected
  List<BridgeGraphProjectionNode> sse_decode_list_bridge_graph_projection_node(
      SseDeserializer deserializer);

  @protected
  List<BridgeRecalledMemory> sse_decode_list_bridge_recalled_memory(
      SseDeserializer deserializer);

  @protected
  List<BridgeSleepMaintenanceIssue>
      sse_decode_list_bridge_sleep_maintenance_issue(
          SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProcessTurnContextItem> sse_decode_list_process_turn_context_item(
      SseDeserializer deserializer);

  @protected
  List<ProcessTurnDetectedAction> sse_decode_list_process_turn_detected_action(
      SseDeserializer deserializer);

  @protected
  List<ProcessTurnPainWarning> sse_decode_list_process_turn_pain_warning(
      SseDeserializer deserializer);

  @protected
  List<ProcessTurnProactiveRecall>
      sse_decode_list_process_turn_proactive_recall(
          SseDeserializer deserializer);

  @protected
  List<ProcessTurnStoredMemory> sse_decode_list_process_turn_stored_memory(
      SseDeserializer deserializer);

  @protected
  List<SearchResult> sse_decode_list_search_result(
      SseDeserializer deserializer);

  @protected
  OpenDatabaseRequest sse_decode_open_database_request(
      SseDeserializer deserializer);

  @protected
  OpenDatabaseResult sse_decode_open_database_result(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ProcessTurnContextItem sse_decode_process_turn_context_item(
      SseDeserializer deserializer);

  @protected
  ProcessTurnDetectedAction sse_decode_process_turn_detected_action(
      SseDeserializer deserializer);

  @protected
  ProcessTurnPainWarning sse_decode_process_turn_pain_warning(
      SseDeserializer deserializer);

  @protected
  ProcessTurnProactiveRecall sse_decode_process_turn_proactive_recall(
      SseDeserializer deserializer);

  @protected
  ProcessTurnRequest sse_decode_process_turn_request(
      SseDeserializer deserializer);

  @protected
  ProcessTurnResult sse_decode_process_turn_result(
      SseDeserializer deserializer);

  @protected
  ProcessTurnStoredMemory sse_decode_process_turn_stored_memory(
      SseDeserializer deserializer);

  @protected
  RecallMemoryContextRequest sse_decode_recall_memory_context_request(
      SseDeserializer deserializer);

  @protected
  RecallMemoryContextResult sse_decode_recall_memory_context_result(
      SseDeserializer deserializer);

  @protected
  RecallQueryRequest sse_decode_recall_query_request(
      SseDeserializer deserializer);

  @protected
  RecallResult sse_decode_recall_result(SseDeserializer deserializer);

  @protected
  RelateMemoriesRequest sse_decode_relate_memories_request(
      SseDeserializer deserializer);

  @protected
  RunSleepMaintenanceRequest sse_decode_run_sleep_maintenance_request(
      SseDeserializer deserializer);

  @protected
  SearchMemoryRequest sse_decode_search_memory_request(
      SseDeserializer deserializer);

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer);

  @protected
  StoreConversationTurnRequest sse_decode_store_conversation_turn_request(
      SseDeserializer deserializer);

  @protected
  StoreConversationTurnResult sse_decode_store_conversation_turn_result(
      SseDeserializer deserializer);

  @protected
  StoreMemoryRequest sse_decode_store_memory_request(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_forget_memory_request(
      ForgetMemoryRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_graph_projection_request(
      GraphProjectionRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ingest_memory_bank_request(
      IngestMemoryBankRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_open_database_request(
      OpenDatabaseRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_process_turn_request(
      ProcessTurnRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_recall_memory_context_request(
      RecallMemoryContextRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_recall_query_request(
      RecallQueryRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_relate_memories_request(
      RelateMemoriesRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_run_sleep_maintenance_request(
      RunSleepMaintenanceRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_search_memory_request(
      SearchMemoryRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_store_conversation_turn_request(
      StoreConversationTurnRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_store_memory_request(
      StoreMemoryRequest self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_edge_type(
      BridgeEdgeType self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_graph_projection(
      BridgeGraphProjection self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_graph_projection_edge(
      BridgeGraphProjectionEdge self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_graph_projection_node(
      BridgeGraphProjectionNode self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_memory_type(
      BridgeMemoryType self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_recalled_memory(
      BridgeRecalledMemory self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_sleep_maintenance_issue(
      BridgeSleepMaintenanceIssue self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_sleep_maintenance_result(
      BridgeSleepMaintenanceResult self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_forget_memory_request(
      ForgetMemoryRequest self, SseSerializer serializer);

  @protected
  void sse_encode_graph_projection_request(
      GraphProjectionRequest self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_ingest_memory_bank_request(
      IngestMemoryBankRequest self, SseSerializer serializer);

  @protected
  void sse_encode_ingest_memory_bank_result(
      IngestMemoryBankResult self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_graph_projection_edge(
      List<BridgeGraphProjectionEdge> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_graph_projection_node(
      List<BridgeGraphProjectionNode> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_recalled_memory(
      List<BridgeRecalledMemory> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_sleep_maintenance_issue(
      List<BridgeSleepMaintenanceIssue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_64_strict(
      Float64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_process_turn_context_item(
      List<ProcessTurnContextItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_process_turn_detected_action(
      List<ProcessTurnDetectedAction> self, SseSerializer serializer);

  @protected
  void sse_encode_list_process_turn_pain_warning(
      List<ProcessTurnPainWarning> self, SseSerializer serializer);

  @protected
  void sse_encode_list_process_turn_proactive_recall(
      List<ProcessTurnProactiveRecall> self, SseSerializer serializer);

  @protected
  void sse_encode_list_process_turn_stored_memory(
      List<ProcessTurnStoredMemory> self, SseSerializer serializer);

  @protected
  void sse_encode_list_search_result(
      List<SearchResult> self, SseSerializer serializer);

  @protected
  void sse_encode_open_database_request(
      OpenDatabaseRequest self, SseSerializer serializer);

  @protected
  void sse_encode_open_database_result(
      OpenDatabaseResult self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_process_turn_context_item(
      ProcessTurnContextItem self, SseSerializer serializer);

  @protected
  void sse_encode_process_turn_detected_action(
      ProcessTurnDetectedAction self, SseSerializer serializer);

  @protected
  void sse_encode_process_turn_pain_warning(
      ProcessTurnPainWarning self, SseSerializer serializer);

  @protected
  void sse_encode_process_turn_proactive_recall(
      ProcessTurnProactiveRecall self, SseSerializer serializer);

  @protected
  void sse_encode_process_turn_request(
      ProcessTurnRequest self, SseSerializer serializer);

  @protected
  void sse_encode_process_turn_result(
      ProcessTurnResult self, SseSerializer serializer);

  @protected
  void sse_encode_process_turn_stored_memory(
      ProcessTurnStoredMemory self, SseSerializer serializer);

  @protected
  void sse_encode_recall_memory_context_request(
      RecallMemoryContextRequest self, SseSerializer serializer);

  @protected
  void sse_encode_recall_memory_context_result(
      RecallMemoryContextResult self, SseSerializer serializer);

  @protected
  void sse_encode_recall_query_request(
      RecallQueryRequest self, SseSerializer serializer);

  @protected
  void sse_encode_recall_result(RecallResult self, SseSerializer serializer);

  @protected
  void sse_encode_relate_memories_request(
      RelateMemoriesRequest self, SseSerializer serializer);

  @protected
  void sse_encode_run_sleep_maintenance_request(
      RunSleepMaintenanceRequest self, SseSerializer serializer);

  @protected
  void sse_encode_search_memory_request(
      SearchMemoryRequest self, SseSerializer serializer);

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer);

  @protected
  void sse_encode_store_conversation_turn_request(
      StoreConversationTurnRequest self, SseSerializer serializer);

  @protected
  void sse_encode_store_conversation_turn_result(
      StoreConversationTurnResult self, SseSerializer serializer);

  @protected
  void sse_encode_store_memory_request(
      StoreMemoryRequest self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
