// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/memory.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiMemoryInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0-beta.2';

  @override
  int get rustContentHash => -1869282923;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mentedb_flutter_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiMemoryCloseDatabase({required int handle});

  Future<void> crateApiMemoryFlushDatabase({required int handle});

  Future<BridgeGraphProjection> crateApiMemoryGraphProjection({
    required GraphProjectionRequest request,
  });

  Future<IngestMemoryBankResult> crateApiMemoryIngestMemoryBank({
    required IngestMemoryBankRequest request,
  });

  Future<void> crateApiMemoryInitApp();

  Future<int> crateApiMemoryMemoryCount({required int handle});

  Future<OpenDatabaseResult> crateApiMemoryOpenDatabase({
    required OpenDatabaseRequest request,
  });

  Future<RecallMemoryContextResult> crateApiMemoryRecallMemoryContext({
    required RecallMemoryContextRequest request,
  });

  Future<BridgeSleepMaintenanceResult> crateApiMemoryRunSleepMaintenance({
    required RunSleepMaintenanceRequest request,
  });

  Future<StoreConversationTurnResult> crateApiMemoryStoreConversationTurn({
    required StoreConversationTurnRequest request,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiMemoryCloseDatabase({required int handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMemoryCloseDatabaseConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryCloseDatabaseConstMeta =>
      const TaskConstMeta(debugName: "close_database", argNames: ["handle"]);

  @override
  Future<void> crateApiMemoryFlushDatabase({required int handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMemoryFlushDatabaseConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryFlushDatabaseConstMeta =>
      const TaskConstMeta(debugName: "flush_database", argNames: ["handle"]);

  @override
  Future<BridgeGraphProjection> crateApiMemoryGraphProjection({
    required GraphProjectionRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_graph_projection_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_graph_projection,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMemoryGraphProjectionConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryGraphProjectionConstMeta =>
      const TaskConstMeta(debugName: "graph_projection", argNames: ["request"]);

  @override
  Future<IngestMemoryBankResult> crateApiMemoryIngestMemoryBank({
    required IngestMemoryBankRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ingest_memory_bank_request(
            request,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ingest_memory_bank_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMemoryIngestMemoryBankConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryIngestMemoryBankConstMeta =>
      const TaskConstMeta(
        debugName: "ingest_memory_bank",
        argNames: ["request"],
      );

  @override
  Future<void> crateApiMemoryInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMemoryInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<int> crateApiMemoryMemoryCount({required int handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMemoryMemoryCountConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryMemoryCountConstMeta =>
      const TaskConstMeta(debugName: "memory_count", argNames: ["handle"]);

  @override
  Future<OpenDatabaseResult> crateApiMemoryOpenDatabase({
    required OpenDatabaseRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_open_database_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_open_database_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMemoryOpenDatabaseConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryOpenDatabaseConstMeta =>
      const TaskConstMeta(debugName: "open_database", argNames: ["request"]);

  @override
  Future<RecallMemoryContextResult> crateApiMemoryRecallMemoryContext({
    required RecallMemoryContextRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_recall_memory_context_request(
            request,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_recall_memory_context_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMemoryRecallMemoryContextConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryRecallMemoryContextConstMeta =>
      const TaskConstMeta(
        debugName: "recall_memory_context",
        argNames: ["request"],
      );

  @override
  Future<BridgeSleepMaintenanceResult> crateApiMemoryRunSleepMaintenance({
    required RunSleepMaintenanceRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_run_sleep_maintenance_request(
            request,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_sleep_maintenance_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMemoryRunSleepMaintenanceConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryRunSleepMaintenanceConstMeta =>
      const TaskConstMeta(
        debugName: "run_sleep_maintenance",
        argNames: ["request"],
      );

  @override
  Future<StoreConversationTurnResult> crateApiMemoryStoreConversationTurn({
    required StoreConversationTurnRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_store_conversation_turn_request(
            request,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_store_conversation_turn_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMemoryStoreConversationTurnConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryStoreConversationTurnConstMeta =>
      const TaskConstMeta(
        debugName: "store_conversation_turn",
        argNames: ["request"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  GraphProjectionRequest dco_decode_box_autoadd_graph_projection_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_graph_projection_request(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  IngestMemoryBankRequest dco_decode_box_autoadd_ingest_memory_bank_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ingest_memory_bank_request(raw);
  }

  @protected
  OpenDatabaseRequest dco_decode_box_autoadd_open_database_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_open_database_request(raw);
  }

  @protected
  RecallMemoryContextRequest
  dco_decode_box_autoadd_recall_memory_context_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_recall_memory_context_request(raw);
  }

  @protected
  RunSleepMaintenanceRequest
  dco_decode_box_autoadd_run_sleep_maintenance_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_run_sleep_maintenance_request(raw);
  }

  @protected
  StoreConversationTurnRequest
  dco_decode_box_autoadd_store_conversation_turn_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_store_conversation_turn_request(raw);
  }

  @protected
  BridgeEdgeType dco_decode_bridge_edge_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeEdgeType.values[raw as int];
  }

  @protected
  BridgeGraphProjection dco_decode_bridge_graph_projection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BridgeGraphProjection(
      nodes: dco_decode_list_bridge_graph_projection_node(arr[0]),
      edges: dco_decode_list_bridge_graph_projection_edge(arr[1]),
      availableNodes: dco_decode_u_32(arr[2]),
      truncated: dco_decode_bool(arr[3]),
    );
  }

  @protected
  BridgeGraphProjectionEdge dco_decode_bridge_graph_projection_edge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BridgeGraphProjectionEdge(
      source: dco_decode_String(arr[0]),
      target: dco_decode_String(arr[1]),
      edgeType: dco_decode_bridge_edge_type(arr[2]),
      weight: dco_decode_f_32(arr[3]),
      label: dco_decode_opt_String(arr[4]),
      createdAtMicros: dco_decode_i_64(arr[5]),
      validUntilMicros: dco_decode_opt_box_autoadd_i_64(arr[6]),
    );
  }

  @protected
  BridgeGraphProjectionNode dco_decode_bridge_graph_projection_node(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return BridgeGraphProjectionNode(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      preview: dco_decode_String(arr[2]),
      memoryType: dco_decode_bridge_memory_type(arr[3]),
      salience: dco_decode_f_32(arr[4]),
      confidence: dco_decode_f_32(arr[5]),
      tags: dco_decode_list_String(arr[6]),
      createdAtMicros: dco_decode_i_64(arr[7]),
      accessedAtMicros: dco_decode_i_64(arr[8]),
      validUntilMicros: dco_decode_opt_box_autoadd_i_64(arr[9]),
      embeddingDim: dco_decode_u_32(arr[10]),
    );
  }

  @protected
  BridgeMemoryType dco_decode_bridge_memory_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeMemoryType.values[raw as int];
  }

  @protected
  BridgeRecalledMemory dco_decode_bridge_recalled_memory(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return BridgeRecalledMemory(
      id: dco_decode_String(arr[0]),
      content: dco_decode_String(arr[1]),
      score: dco_decode_f_32(arr[2]),
      memoryType: dco_decode_bridge_memory_type(arr[3]),
      tags: dco_decode_list_String(arr[4]),
      createdAtMicros: dco_decode_i_64(arr[5]),
      salience: dco_decode_f_32(arr[6]),
      confidence: dco_decode_f_32(arr[7]),
    );
  }

  @protected
  BridgeSleepMaintenanceIssue dco_decode_bridge_sleep_maintenance_issue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BridgeSleepMaintenanceIssue(
      stage: dco_decode_String(arr[0]),
      memoryId: dco_decode_opt_String(arr[1]),
      message: dco_decode_String(arr[2]),
    );
  }

  @protected
  BridgeSleepMaintenanceResult dco_decode_bridge_sleep_maintenance_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 18)
      throw Exception('unexpected arr length: expect 18 but see ${arr.length}');
    return BridgeSleepMaintenanceResult(
      leaseAcquired: dco_decode_bool(arr[0]),
      processedMemories: dco_decode_u_32(arr[1]),
      decayUpdated: dco_decode_u_32(arr[2]),
      archivalEvaluated: dco_decode_u_32(arr[3]),
      archivalKeep: dco_decode_u_32(arr[4]),
      archivalArchive: dco_decode_u_32(arr[5]),
      archivalDelete: dco_decode_u_32(arr[6]),
      archivalConsolidate: dco_decode_u_32(arr[7]),
      archivalDeleteApplied: dco_decode_u_32(arr[8]),
      consolidationCandidates: dco_decode_u_32(arr[9]),
      consolidated: dco_decode_u_32(arr[10]),
      consolidatedMemoryIds: dco_decode_list_String(arr[11]),
      entityPairsLinked: dco_decode_u_32(arr[12]),
      entityEdgesCreated: dco_decode_u_32(arr[13]),
      entityPairsAmbiguous: dco_decode_u_32(arr[14]),
      enrichmentPending: dco_decode_bool(arr[15]),
      enrichmentCandidates: dco_decode_u_32(arr[16]),
      issues: dco_decode_list_bridge_sleep_maintenance_issue(arr[17]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GraphProjectionRequest dco_decode_graph_projection_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return GraphProjectionRequest(
      handle: dco_decode_u_32(arr[0]),
      center: dco_decode_opt_String(arr[1]),
      depth: dco_decode_u_32(arr[2]),
      limit: dco_decode_u_32(arr[3]),
      labelChars: dco_decode_u_32(arr[4]),
      previewChars: dco_decode_u_32(arr[5]),
      includeInvalidated: dco_decode_bool(arr[6]),
      includeEdges: dco_decode_bool(arr[7]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IngestMemoryBankRequest dco_decode_ingest_memory_bank_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return IngestMemoryBankRequest(
      handle: dco_decode_u_32(arr[0]),
      text: dco_decode_String(arr[1]),
      source: dco_decode_String(arr[2]),
      memoryType: dco_decode_bridge_memory_type(arr[3]),
      maxChunkChars: dco_decode_u_32(arr[4]),
      replaceSource: dco_decode_bool(arr[5]),
      flush: dco_decode_bool(arr[6]),
    );
  }

  @protected
  IngestMemoryBankResult dco_decode_ingest_memory_bank_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return IngestMemoryBankResult(
      stored: dco_decode_u_32(arr[0]),
      replaced: dco_decode_u_32(arr[1]),
      memoryCount: dco_decode_u_32(arr[2]),
      memoryIds: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BridgeGraphProjectionEdge> dco_decode_list_bridge_graph_projection_edge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_bridge_graph_projection_edge)
        .toList();
  }

  @protected
  List<BridgeGraphProjectionNode> dco_decode_list_bridge_graph_projection_node(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_bridge_graph_projection_node)
        .toList();
  }

  @protected
  List<BridgeRecalledMemory> dco_decode_list_bridge_recalled_memory(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_bridge_recalled_memory)
        .toList();
  }

  @protected
  List<BridgeSleepMaintenanceIssue>
  dco_decode_list_bridge_sleep_maintenance_issue(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_bridge_sleep_maintenance_issue)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  OpenDatabaseRequest dco_decode_open_database_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OpenDatabaseRequest(
      path: dco_decode_String(arr[0]),
      embeddingDimensions: dco_decode_u_32(arr[1]),
      agentId: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  OpenDatabaseResult dco_decode_open_database_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return OpenDatabaseResult(
      handle: dco_decode_u_32(arr[0]),
      path: dco_decode_String(arr[1]),
      agentId: dco_decode_String(arr[2]),
      embeddingDimensions: dco_decode_u_32(arr[3]),
      memoryCount: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  RecallMemoryContextRequest dco_decode_recall_memory_context_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RecallMemoryContextRequest(
      handle: dco_decode_u_32(arr[0]),
      query: dco_decode_String(arr[1]),
      limit: dco_decode_u_32(arr[2]),
      maxContextChars: dco_decode_u_32(arr[3]),
      source: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  RecallMemoryContextResult dco_decode_recall_memory_context_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RecallMemoryContextResult(
      context: dco_decode_String(arr[0]),
      memories: dco_decode_list_bridge_recalled_memory(arr[1]),
      truncated: dco_decode_bool(arr[2]),
    );
  }

  @protected
  RunSleepMaintenanceRequest dco_decode_run_sleep_maintenance_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return RunSleepMaintenanceRequest(
      handle: dco_decode_u_32(arr[0]),
      maxMemories: dco_decode_u_32(arr[1]),
      applyDecay: dco_decode_bool(arr[2]),
      evaluateArchival: dco_decode_bool(arr[3]),
      applyArchivalDeletes: dco_decode_bool(arr[4]),
      runConsolidation: dco_decode_bool(arr[5]),
      maxConsolidationClusters: dco_decode_u_32(arr[6]),
      consolidationMinClusterSize: dco_decode_u_32(arr[7]),
      consolidationSimilarityThreshold: dco_decode_f_32(arr[8]),
      linkEntities: dco_decode_bool(arr[9]),
    );
  }

  @protected
  StoreConversationTurnRequest dco_decode_store_conversation_turn_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return StoreConversationTurnRequest(
      handle: dco_decode_u_32(arr[0]),
      conversationId: dco_decode_String(arr[1]),
      turnIndex: dco_decode_u_32(arr[2]),
      userMessage: dco_decode_String(arr[3]),
      assistantMessage: dco_decode_String(arr[4]),
      source: dco_decode_String(arr[5]),
      flush: dco_decode_bool(arr[6]),
    );
  }

  @protected
  StoreConversationTurnResult dco_decode_store_conversation_turn_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return StoreConversationTurnResult(
      stored: dco_decode_u_32(arr[0]),
      userMemoryId: dco_decode_String(arr[1]),
      assistantMemoryId: dco_decode_String(arr[2]),
      memoryCount: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  GraphProjectionRequest sse_decode_box_autoadd_graph_projection_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_graph_projection_request(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  IngestMemoryBankRequest sse_decode_box_autoadd_ingest_memory_bank_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ingest_memory_bank_request(deserializer));
  }

  @protected
  OpenDatabaseRequest sse_decode_box_autoadd_open_database_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_open_database_request(deserializer));
  }

  @protected
  RecallMemoryContextRequest
  sse_decode_box_autoadd_recall_memory_context_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_recall_memory_context_request(deserializer));
  }

  @protected
  RunSleepMaintenanceRequest
  sse_decode_box_autoadd_run_sleep_maintenance_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_run_sleep_maintenance_request(deserializer));
  }

  @protected
  StoreConversationTurnRequest
  sse_decode_box_autoadd_store_conversation_turn_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_store_conversation_turn_request(deserializer));
  }

  @protected
  BridgeEdgeType sse_decode_bridge_edge_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeEdgeType.values[inner];
  }

  @protected
  BridgeGraphProjection sse_decode_bridge_graph_projection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodes = sse_decode_list_bridge_graph_projection_node(deserializer);
    var var_edges = sse_decode_list_bridge_graph_projection_edge(deserializer);
    var var_availableNodes = sse_decode_u_32(deserializer);
    var var_truncated = sse_decode_bool(deserializer);
    return BridgeGraphProjection(
      nodes: var_nodes,
      edges: var_edges,
      availableNodes: var_availableNodes,
      truncated: var_truncated,
    );
  }

  @protected
  BridgeGraphProjectionEdge sse_decode_bridge_graph_projection_edge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_source = sse_decode_String(deserializer);
    var var_target = sse_decode_String(deserializer);
    var var_edgeType = sse_decode_bridge_edge_type(deserializer);
    var var_weight = sse_decode_f_32(deserializer);
    var var_label = sse_decode_opt_String(deserializer);
    var var_createdAtMicros = sse_decode_i_64(deserializer);
    var var_validUntilMicros = sse_decode_opt_box_autoadd_i_64(deserializer);
    return BridgeGraphProjectionEdge(
      source: var_source,
      target: var_target,
      edgeType: var_edgeType,
      weight: var_weight,
      label: var_label,
      createdAtMicros: var_createdAtMicros,
      validUntilMicros: var_validUntilMicros,
    );
  }

  @protected
  BridgeGraphProjectionNode sse_decode_bridge_graph_projection_node(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_preview = sse_decode_String(deserializer);
    var var_memoryType = sse_decode_bridge_memory_type(deserializer);
    var var_salience = sse_decode_f_32(deserializer);
    var var_confidence = sse_decode_f_32(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_createdAtMicros = sse_decode_i_64(deserializer);
    var var_accessedAtMicros = sse_decode_i_64(deserializer);
    var var_validUntilMicros = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_embeddingDim = sse_decode_u_32(deserializer);
    return BridgeGraphProjectionNode(
      id: var_id,
      label: var_label,
      preview: var_preview,
      memoryType: var_memoryType,
      salience: var_salience,
      confidence: var_confidence,
      tags: var_tags,
      createdAtMicros: var_createdAtMicros,
      accessedAtMicros: var_accessedAtMicros,
      validUntilMicros: var_validUntilMicros,
      embeddingDim: var_embeddingDim,
    );
  }

  @protected
  BridgeMemoryType sse_decode_bridge_memory_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeMemoryType.values[inner];
  }

  @protected
  BridgeRecalledMemory sse_decode_bridge_recalled_memory(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    var var_memoryType = sse_decode_bridge_memory_type(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_createdAtMicros = sse_decode_i_64(deserializer);
    var var_salience = sse_decode_f_32(deserializer);
    var var_confidence = sse_decode_f_32(deserializer);
    return BridgeRecalledMemory(
      id: var_id,
      content: var_content,
      score: var_score,
      memoryType: var_memoryType,
      tags: var_tags,
      createdAtMicros: var_createdAtMicros,
      salience: var_salience,
      confidence: var_confidence,
    );
  }

  @protected
  BridgeSleepMaintenanceIssue sse_decode_bridge_sleep_maintenance_issue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stage = sse_decode_String(deserializer);
    var var_memoryId = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return BridgeSleepMaintenanceIssue(
      stage: var_stage,
      memoryId: var_memoryId,
      message: var_message,
    );
  }

  @protected
  BridgeSleepMaintenanceResult sse_decode_bridge_sleep_maintenance_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_leaseAcquired = sse_decode_bool(deserializer);
    var var_processedMemories = sse_decode_u_32(deserializer);
    var var_decayUpdated = sse_decode_u_32(deserializer);
    var var_archivalEvaluated = sse_decode_u_32(deserializer);
    var var_archivalKeep = sse_decode_u_32(deserializer);
    var var_archivalArchive = sse_decode_u_32(deserializer);
    var var_archivalDelete = sse_decode_u_32(deserializer);
    var var_archivalConsolidate = sse_decode_u_32(deserializer);
    var var_archivalDeleteApplied = sse_decode_u_32(deserializer);
    var var_consolidationCandidates = sse_decode_u_32(deserializer);
    var var_consolidated = sse_decode_u_32(deserializer);
    var var_consolidatedMemoryIds = sse_decode_list_String(deserializer);
    var var_entityPairsLinked = sse_decode_u_32(deserializer);
    var var_entityEdgesCreated = sse_decode_u_32(deserializer);
    var var_entityPairsAmbiguous = sse_decode_u_32(deserializer);
    var var_enrichmentPending = sse_decode_bool(deserializer);
    var var_enrichmentCandidates = sse_decode_u_32(deserializer);
    var var_issues = sse_decode_list_bridge_sleep_maintenance_issue(
      deserializer,
    );
    return BridgeSleepMaintenanceResult(
      leaseAcquired: var_leaseAcquired,
      processedMemories: var_processedMemories,
      decayUpdated: var_decayUpdated,
      archivalEvaluated: var_archivalEvaluated,
      archivalKeep: var_archivalKeep,
      archivalArchive: var_archivalArchive,
      archivalDelete: var_archivalDelete,
      archivalConsolidate: var_archivalConsolidate,
      archivalDeleteApplied: var_archivalDeleteApplied,
      consolidationCandidates: var_consolidationCandidates,
      consolidated: var_consolidated,
      consolidatedMemoryIds: var_consolidatedMemoryIds,
      entityPairsLinked: var_entityPairsLinked,
      entityEdgesCreated: var_entityEdgesCreated,
      entityPairsAmbiguous: var_entityPairsAmbiguous,
      enrichmentPending: var_enrichmentPending,
      enrichmentCandidates: var_enrichmentCandidates,
      issues: var_issues,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  GraphProjectionRequest sse_decode_graph_projection_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_u_32(deserializer);
    var var_center = sse_decode_opt_String(deserializer);
    var var_depth = sse_decode_u_32(deserializer);
    var var_limit = sse_decode_u_32(deserializer);
    var var_labelChars = sse_decode_u_32(deserializer);
    var var_previewChars = sse_decode_u_32(deserializer);
    var var_includeInvalidated = sse_decode_bool(deserializer);
    var var_includeEdges = sse_decode_bool(deserializer);
    return GraphProjectionRequest(
      handle: var_handle,
      center: var_center,
      depth: var_depth,
      limit: var_limit,
      labelChars: var_labelChars,
      previewChars: var_previewChars,
      includeInvalidated: var_includeInvalidated,
      includeEdges: var_includeEdges,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IngestMemoryBankRequest sse_decode_ingest_memory_bank_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_u_32(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_memoryType = sse_decode_bridge_memory_type(deserializer);
    var var_maxChunkChars = sse_decode_u_32(deserializer);
    var var_replaceSource = sse_decode_bool(deserializer);
    var var_flush = sse_decode_bool(deserializer);
    return IngestMemoryBankRequest(
      handle: var_handle,
      text: var_text,
      source: var_source,
      memoryType: var_memoryType,
      maxChunkChars: var_maxChunkChars,
      replaceSource: var_replaceSource,
      flush: var_flush,
    );
  }

  @protected
  IngestMemoryBankResult sse_decode_ingest_memory_bank_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stored = sse_decode_u_32(deserializer);
    var var_replaced = sse_decode_u_32(deserializer);
    var var_memoryCount = sse_decode_u_32(deserializer);
    var var_memoryIds = sse_decode_list_String(deserializer);
    return IngestMemoryBankResult(
      stored: var_stored,
      replaced: var_replaced,
      memoryCount: var_memoryCount,
      memoryIds: var_memoryIds,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeGraphProjectionEdge> sse_decode_list_bridge_graph_projection_edge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeGraphProjectionEdge>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_graph_projection_edge(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeGraphProjectionNode> sse_decode_list_bridge_graph_projection_node(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeGraphProjectionNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_graph_projection_node(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeRecalledMemory> sse_decode_list_bridge_recalled_memory(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeRecalledMemory>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_recalled_memory(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeSleepMaintenanceIssue>
  sse_decode_list_bridge_sleep_maintenance_issue(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeSleepMaintenanceIssue>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_sleep_maintenance_issue(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  OpenDatabaseRequest sse_decode_open_database_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_embeddingDimensions = sse_decode_u_32(deserializer);
    var var_agentId = sse_decode_opt_String(deserializer);
    return OpenDatabaseRequest(
      path: var_path,
      embeddingDimensions: var_embeddingDimensions,
      agentId: var_agentId,
    );
  }

  @protected
  OpenDatabaseResult sse_decode_open_database_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_u_32(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_agentId = sse_decode_String(deserializer);
    var var_embeddingDimensions = sse_decode_u_32(deserializer);
    var var_memoryCount = sse_decode_u_32(deserializer);
    return OpenDatabaseResult(
      handle: var_handle,
      path: var_path,
      agentId: var_agentId,
      embeddingDimensions: var_embeddingDimensions,
      memoryCount: var_memoryCount,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RecallMemoryContextRequest sse_decode_recall_memory_context_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_u_32(deserializer);
    var var_query = sse_decode_String(deserializer);
    var var_limit = sse_decode_u_32(deserializer);
    var var_maxContextChars = sse_decode_u_32(deserializer);
    var var_source = sse_decode_opt_String(deserializer);
    return RecallMemoryContextRequest(
      handle: var_handle,
      query: var_query,
      limit: var_limit,
      maxContextChars: var_maxContextChars,
      source: var_source,
    );
  }

  @protected
  RecallMemoryContextResult sse_decode_recall_memory_context_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_context = sse_decode_String(deserializer);
    var var_memories = sse_decode_list_bridge_recalled_memory(deserializer);
    var var_truncated = sse_decode_bool(deserializer);
    return RecallMemoryContextResult(
      context: var_context,
      memories: var_memories,
      truncated: var_truncated,
    );
  }

  @protected
  RunSleepMaintenanceRequest sse_decode_run_sleep_maintenance_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_u_32(deserializer);
    var var_maxMemories = sse_decode_u_32(deserializer);
    var var_applyDecay = sse_decode_bool(deserializer);
    var var_evaluateArchival = sse_decode_bool(deserializer);
    var var_applyArchivalDeletes = sse_decode_bool(deserializer);
    var var_runConsolidation = sse_decode_bool(deserializer);
    var var_maxConsolidationClusters = sse_decode_u_32(deserializer);
    var var_consolidationMinClusterSize = sse_decode_u_32(deserializer);
    var var_consolidationSimilarityThreshold = sse_decode_f_32(deserializer);
    var var_linkEntities = sse_decode_bool(deserializer);
    return RunSleepMaintenanceRequest(
      handle: var_handle,
      maxMemories: var_maxMemories,
      applyDecay: var_applyDecay,
      evaluateArchival: var_evaluateArchival,
      applyArchivalDeletes: var_applyArchivalDeletes,
      runConsolidation: var_runConsolidation,
      maxConsolidationClusters: var_maxConsolidationClusters,
      consolidationMinClusterSize: var_consolidationMinClusterSize,
      consolidationSimilarityThreshold: var_consolidationSimilarityThreshold,
      linkEntities: var_linkEntities,
    );
  }

  @protected
  StoreConversationTurnRequest sse_decode_store_conversation_turn_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_u_32(deserializer);
    var var_conversationId = sse_decode_String(deserializer);
    var var_turnIndex = sse_decode_u_32(deserializer);
    var var_userMessage = sse_decode_String(deserializer);
    var var_assistantMessage = sse_decode_String(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_flush = sse_decode_bool(deserializer);
    return StoreConversationTurnRequest(
      handle: var_handle,
      conversationId: var_conversationId,
      turnIndex: var_turnIndex,
      userMessage: var_userMessage,
      assistantMessage: var_assistantMessage,
      source: var_source,
      flush: var_flush,
    );
  }

  @protected
  StoreConversationTurnResult sse_decode_store_conversation_turn_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stored = sse_decode_u_32(deserializer);
    var var_userMemoryId = sse_decode_String(deserializer);
    var var_assistantMemoryId = sse_decode_String(deserializer);
    var var_memoryCount = sse_decode_u_32(deserializer);
    return StoreConversationTurnResult(
      stored: var_stored,
      userMemoryId: var_userMemoryId,
      assistantMemoryId: var_assistantMemoryId,
      memoryCount: var_memoryCount,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_graph_projection_request(
    GraphProjectionRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_graph_projection_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ingest_memory_bank_request(
    IngestMemoryBankRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ingest_memory_bank_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_open_database_request(
    OpenDatabaseRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_open_database_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_recall_memory_context_request(
    RecallMemoryContextRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_recall_memory_context_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_run_sleep_maintenance_request(
    RunSleepMaintenanceRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_run_sleep_maintenance_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_store_conversation_turn_request(
    StoreConversationTurnRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_store_conversation_turn_request(self, serializer);
  }

  @protected
  void sse_encode_bridge_edge_type(
    BridgeEdgeType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bridge_graph_projection(
    BridgeGraphProjection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_bridge_graph_projection_node(self.nodes, serializer);
    sse_encode_list_bridge_graph_projection_edge(self.edges, serializer);
    sse_encode_u_32(self.availableNodes, serializer);
    sse_encode_bool(self.truncated, serializer);
  }

  @protected
  void sse_encode_bridge_graph_projection_edge(
    BridgeGraphProjectionEdge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.source, serializer);
    sse_encode_String(self.target, serializer);
    sse_encode_bridge_edge_type(self.edgeType, serializer);
    sse_encode_f_32(self.weight, serializer);
    sse_encode_opt_String(self.label, serializer);
    sse_encode_i_64(self.createdAtMicros, serializer);
    sse_encode_opt_box_autoadd_i_64(self.validUntilMicros, serializer);
  }

  @protected
  void sse_encode_bridge_graph_projection_node(
    BridgeGraphProjectionNode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.preview, serializer);
    sse_encode_bridge_memory_type(self.memoryType, serializer);
    sse_encode_f_32(self.salience, serializer);
    sse_encode_f_32(self.confidence, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_i_64(self.createdAtMicros, serializer);
    sse_encode_i_64(self.accessedAtMicros, serializer);
    sse_encode_opt_box_autoadd_i_64(self.validUntilMicros, serializer);
    sse_encode_u_32(self.embeddingDim, serializer);
  }

  @protected
  void sse_encode_bridge_memory_type(
    BridgeMemoryType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bridge_recalled_memory(
    BridgeRecalledMemory self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_f_32(self.score, serializer);
    sse_encode_bridge_memory_type(self.memoryType, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_i_64(self.createdAtMicros, serializer);
    sse_encode_f_32(self.salience, serializer);
    sse_encode_f_32(self.confidence, serializer);
  }

  @protected
  void sse_encode_bridge_sleep_maintenance_issue(
    BridgeSleepMaintenanceIssue self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.stage, serializer);
    sse_encode_opt_String(self.memoryId, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_bridge_sleep_maintenance_result(
    BridgeSleepMaintenanceResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.leaseAcquired, serializer);
    sse_encode_u_32(self.processedMemories, serializer);
    sse_encode_u_32(self.decayUpdated, serializer);
    sse_encode_u_32(self.archivalEvaluated, serializer);
    sse_encode_u_32(self.archivalKeep, serializer);
    sse_encode_u_32(self.archivalArchive, serializer);
    sse_encode_u_32(self.archivalDelete, serializer);
    sse_encode_u_32(self.archivalConsolidate, serializer);
    sse_encode_u_32(self.archivalDeleteApplied, serializer);
    sse_encode_u_32(self.consolidationCandidates, serializer);
    sse_encode_u_32(self.consolidated, serializer);
    sse_encode_list_String(self.consolidatedMemoryIds, serializer);
    sse_encode_u_32(self.entityPairsLinked, serializer);
    sse_encode_u_32(self.entityEdgesCreated, serializer);
    sse_encode_u_32(self.entityPairsAmbiguous, serializer);
    sse_encode_bool(self.enrichmentPending, serializer);
    sse_encode_u_32(self.enrichmentCandidates, serializer);
    sse_encode_list_bridge_sleep_maintenance_issue(self.issues, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_graph_projection_request(
    GraphProjectionRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.handle, serializer);
    sse_encode_opt_String(self.center, serializer);
    sse_encode_u_32(self.depth, serializer);
    sse_encode_u_32(self.limit, serializer);
    sse_encode_u_32(self.labelChars, serializer);
    sse_encode_u_32(self.previewChars, serializer);
    sse_encode_bool(self.includeInvalidated, serializer);
    sse_encode_bool(self.includeEdges, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_ingest_memory_bank_request(
    IngestMemoryBankRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.handle, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_bridge_memory_type(self.memoryType, serializer);
    sse_encode_u_32(self.maxChunkChars, serializer);
    sse_encode_bool(self.replaceSource, serializer);
    sse_encode_bool(self.flush, serializer);
  }

  @protected
  void sse_encode_ingest_memory_bank_result(
    IngestMemoryBankResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.stored, serializer);
    sse_encode_u_32(self.replaced, serializer);
    sse_encode_u_32(self.memoryCount, serializer);
    sse_encode_list_String(self.memoryIds, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_graph_projection_edge(
    List<BridgeGraphProjectionEdge> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_graph_projection_edge(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_graph_projection_node(
    List<BridgeGraphProjectionNode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_graph_projection_node(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_recalled_memory(
    List<BridgeRecalledMemory> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_recalled_memory(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_sleep_maintenance_issue(
    List<BridgeSleepMaintenanceIssue> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_sleep_maintenance_issue(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_open_database_request(
    OpenDatabaseRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_u_32(self.embeddingDimensions, serializer);
    sse_encode_opt_String(self.agentId, serializer);
  }

  @protected
  void sse_encode_open_database_result(
    OpenDatabaseResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.handle, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.agentId, serializer);
    sse_encode_u_32(self.embeddingDimensions, serializer);
    sse_encode_u_32(self.memoryCount, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_recall_memory_context_request(
    RecallMemoryContextRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.handle, serializer);
    sse_encode_String(self.query, serializer);
    sse_encode_u_32(self.limit, serializer);
    sse_encode_u_32(self.maxContextChars, serializer);
    sse_encode_opt_String(self.source, serializer);
  }

  @protected
  void sse_encode_recall_memory_context_result(
    RecallMemoryContextResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.context, serializer);
    sse_encode_list_bridge_recalled_memory(self.memories, serializer);
    sse_encode_bool(self.truncated, serializer);
  }

  @protected
  void sse_encode_run_sleep_maintenance_request(
    RunSleepMaintenanceRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.handle, serializer);
    sse_encode_u_32(self.maxMemories, serializer);
    sse_encode_bool(self.applyDecay, serializer);
    sse_encode_bool(self.evaluateArchival, serializer);
    sse_encode_bool(self.applyArchivalDeletes, serializer);
    sse_encode_bool(self.runConsolidation, serializer);
    sse_encode_u_32(self.maxConsolidationClusters, serializer);
    sse_encode_u_32(self.consolidationMinClusterSize, serializer);
    sse_encode_f_32(self.consolidationSimilarityThreshold, serializer);
    sse_encode_bool(self.linkEntities, serializer);
  }

  @protected
  void sse_encode_store_conversation_turn_request(
    StoreConversationTurnRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.handle, serializer);
    sse_encode_String(self.conversationId, serializer);
    sse_encode_u_32(self.turnIndex, serializer);
    sse_encode_String(self.userMessage, serializer);
    sse_encode_String(self.assistantMessage, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_bool(self.flush, serializer);
  }

  @protected
  void sse_encode_store_conversation_turn_result(
    StoreConversationTurnResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.stored, serializer);
    sse_encode_String(self.userMemoryId, serializer);
    sse_encode_String(self.assistantMemoryId, serializer);
    sse_encode_u_32(self.memoryCount, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
